export { default as ZTabs, tabsProps } from './src/Tabs'
export type { TabsProps } from './src/Tabs'
export { default as ZTabPane, tabPaneProps } from './src/TabPane'
export type { TabPaneProps } from './src/TabPane'
export { default as ZTab, tabProps } from './src/Tab'
export type { TabProps } from './src/Tab'
export type { TabsInst } from './src/interface'
