import type { GlobalThemeOverrides } from '@zeta-gds/components'

export const colors = {
  primaryColor: '#9DA2BF'
}

export const themeOverridesDark: GlobalThemeOverrides = {
  common: {
    ...colors,
    fontFamily:
      '"IBM Plex Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    fontFamilyMono:
      '"IBM Plex Mono", SFMono-Regular, Menlo, Consolas, Courier, monospace'
  },
  Anchor: {
    borderRadius: '0',
    railColor: 'var(--gds-color-border-neutral)',
    railColorActive: 'var(--gds-color-border-primary)',
    linkColor: 'var(--gds-color-bg-primary-light1)',
    linkTextColor: 'var(--gds-color-text-neutral-light2)',
    linkTextColorHover: 'var(--gds-color-text-primary)',
    linkTextColorPressed: 'var(--gds-color-text-primary-dark1)',
    linkTextColorActive: 'var(--gds-color-text-primary)'
  },
  Badge: {
    colorPrimary: 'var(--gds-color-bg-primary)',
    colorInfo: 'var(--gds-color-bg-info)',
    colorSuccess: 'var(--gds-color-bg-success)',
    colorError: 'var(--gds-color-bg-danger)',
    colorWarning: 'var(--gds-color-bg-warning)'
  },
  Dropdown: {
    // non-inverted
    optionTextColor: 'var(--gds-color-text-neutral)',
    optionTextColorHover: 'var(--gds-color-text-neutral)',
    optionTextColorActive: 'var(--gds-color-text-primary)',
    optionTextColorChildActive: 'var(--gds-color-text-primary)',
    color: 'var(--gds-color-bg-dark)',
    dividerColor: 'var(--gds-color-border-neutral)',
    suffixColor: 'var(--gds-color-text-neutral)',
    prefixColor: 'var(--gds-color-text-neutral)',
    optionColorHover: 'var(--gds-color-bg-neutral-dark1)',
    optionColorActive: 'var(--gds-color-bg-primary-light1)',
    groupHeaderTextColor: 'var(--gds-color-text-neutral)',
    //  inverted
    optionTextColorInverted: 'var(--gds-color-text-neutral)',
    optionTextColorHoverInverted: 'var(--gds-color-text-neutral)',
    optionTextColorActiveInverted: 'var(--gds-color-text-primary)',
    optionTextColorChildActiveInverted: 'var(--gds-color-text-primary)',
    colorInverted: 'var(--gds-color-bg-nav-dark)',
    dividerColorInverted: 'var(--gds-color-border-neutral)',
    suffixColorInverted: 'var(--gds-color-text-neutral)',
    prefixColorInverted: 'var(--gds-color-text-neutral)',
    optionColorHoverInverted: 'var(--gds-color-bg-neutral-dark1)',
    optionColorActiveInverted: 'var(--gds-color-bg-neutral-light1)',
    groupHeaderTextColorInverted: 'var(--gds-color-text-neutral)',
    optionOpacityDisabled: '0.4',
    optionIconColor: 'var(--gds-color-icon-neutral)'
  },
  Switch: {
    opacityDisabled: '0.4',
    iconColor: 'var(--gds-color-icon-neutral)',
    textColor: 'var(--gds-color-text-light)',
    loadingColor: 'var(--gds-color-border-primary)',
    railColor: 'var(--gds-color-bg-neutral-dark2)',
    railColorHover: 'var(--gds-color-bg-neutral-dark3)',
    railColorActive: 'var(--gds-color-bg-primary)',
    railColorActiveHover: 'var(--gds-color-bg-primary-dark1)',
    buttonColor: 'var(--gds-color-bg-button-secondary)',
    railBorderRadiusSmall: 'var(--gds-border-radius-xs)',
    railBorderRadiusMedium: 'var(--gds-border-radius-xs)',
    railBorderRadiusLarge: 'var(--gds-border-radius-xs)',
    buttonBorderRadiusSmall: 'var(--gds-border-radius-xs)',
    buttonBorderRadiusMedium: 'var(--gds-border-radius-xs)',
    buttonBorderRadiusLarge: 'var(--gds-border-radius-xs)',
    boxShadowFocus: '0 0 0 2px var(--gds-color-border-primary)',
    buttonBoxShadow: `0px 4px 8px -2px hsla(231, 95%, 15%, 0.25),
    0px 0px 1px 0px hsla(231, 95%, 15%, 0.3)`
  },
  Layout: {
    headerColorInverted: 'var(--gds-color-bg-nav-dark)',
    toggleButtonColor: 'white',
    invertToggleButtonColor: 'white',
    siderToggleButtonIconColorInverted: 'black',
    siderToggleButtonIconColor: 'black',
    siderOverlayShadow:
      '0px 0px 1px 0px rgba(2, 13, 75, 0.30), 0px 4px 10px -2px rgba(2, 13, 75, 0.30)',
    siderResizeBarColor: '#2A4FF0',
    siderResizeIconColor: '#7D83A6',
    siderResizeBorderColor: '#E6E7F2'
  },
  Checkbox: {
    color: 'var(--gds-color-bg-light)',
    border: '2px solid var(--gds-color-border-neutral-dark2)',
    borderChecked: '2px solid var(--gds-color-border-primary)',
    colorChecked: 'var(--gds-color-bg-primary)',
    textColor: '#FFF',
    colorCheckedHover: 'orange',
    borderRadius: '4px'
  },
  Radio: {
    labelLineHeight: '1.6',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    dotColorActive: 'var(--gds-color-bg-primary)',
    dotColorDisabled: 'var(--gds-color-border-neutral-dark2)',
    buttonTextColor: 'var(--gds-color-text-neutral-light1)',
    buttonBorderColor: 'var(--gds-color-border-neutral-dark2)',
    buttonBorderColorActive: 'var(--gds-color-border-primary-light)',
    buttonBorderColorHover: 'var(--gds-color-border-neutral-dark3)',
    buttonBackgroundColorActive: 'var(--gds-color-bg-primary-light2)',
    buttonBackgroundColorHover: 'var(--gds-color-bg-neutral)',
    buttonTextColorHover: 'var(--gds-color-text-primary)',
    dotColorHoverActive: 'var(--gds-color-bg-primary)',
    buttonBackgroundColorHoverActive: 'var(--gds-color-bg-primary-light2)',
    opacityDisabled: '40%',
    boxShadow: 'inset 0 0 0 2px var(--gds-color-bg-neutral-dark2)',
    boxShadowActive: 'inset 0 0 0 2px var(--gds-color-bg-primary)',
    boxShadowActiveHover: 'inset 0 0 0 2px var(--gds-color-bg-neutral-dark2)',
    boxShadowHover: 'inset 0 0 0 2px var(--gds-color-bg-primary-dark1)',
    boxShadowDisabled: 'inset 0 0 0 2px var(--gds-color-bg-neutral-light2)',
    buttonBoxShadowFocus: 'inset 0 0 0 2px var(--gds-color-bg-primary)',
    boxShadowFocus:
      'inset 0 0 0 2px var(--gds-color-bg-primary), 0 0 0 2px var(--gds-color-bg-primary)',
    buttonBorderRadius: 'var(--gds-border-radius-xs)',
    iconColor: 'white',
    iconSelectedColor: colors.primaryColor,
    buttonTextColorActive: colors.primaryColor
  },
  Drawer: {
    bodyPadding: '16px 24px',
    headerPadding: '16px 24px',
    footerPadding: '24px 24px',
    color: 'var(--gds-color-bg-light)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    closeIconColor: 'var(--gds-color-icon-neutral-dark1)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    descriptionTextColor: 'var(--gds-color-text-neutral-light2)',
    titleFontSize: 'var(--gds-font-size-20)',
    headerBorderBottom: '1px solid var(--gds-color-border-neutral)',
    footerBorderTop: '1px solid var(--gds-color-border-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    closeSize: '36px',
    closeIconSize: '20px',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    closeColorHover: 'var(--gds-color-bg-neutral)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark1)',
    resizableTriggerColorHover: 'var(--gds-color-bg-primary-dark1)',
    titleFontWeight: 500,
    lineHeight: '1.6'
  },
  Code: {
    lineNumberBackgroundColor: 'var(--gds-color-bg-neutral-dark1)',
    'mono-3': '#5E658D',
    'hue-1': '#2AB2F0',
    'hue-2': '#F04F6D',
    'hue-3': '#B27AFF',
    'hue-4': '#49CF55',
    'hue-5': '#4F71FF',
    'hue-5-2': '#BE304A',
    'hue-6': '#F09948',
    'hue-6-2': '#FF6FC5'
  },
  Button: {
    // border
    border: '1px solid var(--gds-color-border-button-secondary)',
    borderHover: '1px solid var(--gds-color-border-button-secondary-dark1)',
    borderPressed: '1px solid var(--gds-color-border-button-secondary-dark2)',
    borderFocus: '1px solid var(--gds-color-border-button-secondary-dark2)',
    borderDisabled: '1px solid var(--gds-color-border-button-secondary)',
    borderNeutral: '1px solid var(--gds-color-border-button-secondary)',
    borderHoverNeutral:
      '1px solid var(--gds-color-border-button-secondary-dark1)',
    borderPressedNeutral:
      '1px solid var(--gds-color-border-button-secondary-dark2)',
    borderFocusNeutral:
      '1px solid var(--gds-color-border-button-secondary-dark2)',
    borderDisabledNeutral: '1px solid var(--gds-color-border-button-secondary)',
    borderPrimary: '1px solid var(--gds-color-border-primary)',
    borderHoverPrimary: '1px solid var(--gds-color-border-primary)',
    borderPressedPrimary: '1px solid var(--gds-color-border-primary)',
    borderFocusPrimary: '1px solid var(--gds-color-border-primary)',
    borderDisabledPrimary: '1px solid var(--gds-color-border-primary)',
    borderInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderHoverInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderPressedInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderFocusInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderDisabledInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderSuccess: '1px solid var(--gds-color-text-success)',
    borderHoverSuccess: '1px solid var(--gds-color-text-success)',
    borderPressedSuccess: '1px solid var(--gds-color-text-success)',
    borderFocusSuccess: '1px solid var(--gds-color-text-success)',
    borderDisabledSuccess: '1px solid var(--gds-color-text-success)',
    borderWarning: '1px solid var(--gds-color-text-warning)',
    borderHoverWarning: '1px solid var(--gds-color-text-warning)',
    borderPressedWarning: '1px solid var(--gds-color-text-warning)',
    borderFocusWarning: '1px solid var(--gds-color-text-warning)',
    borderDisabledWarning: '1px solid var(--gds-color-text-warning)',
    borderError: '1px solid var(--gds-color-bg-button-danger-primary)',
    borderHoverError:
      '1px solid var(--gds-color-bg-button-danger-primary-dark1)',
    borderPressedError:
      '1px solid var(--gds-color-bg-button-danger-primary-dark2)',
    borderFocusError:
      '1px solid var(--gds-color-bg-button-danger-primary-dark2)',
    borderDisabledError: '1px solid var(--gds-color-bg-button-danger-primary)',

    // text color
    // filled
    textColorFilled: 'var(--gds-color-text-light)',
    iconColorFilled: 'var(--gds-color-text-light)',
    textColorHoverFilled: 'var(--gds-color-text-light)',
    textColorPressedFilled: 'var(--gds-color-text-light)',
    textColorFocusFilled: 'var(--gds-color-text-light)',
    textColorDisabledFilled: 'var(--gds-color-text-light)',
    textColorFilledNeutral: 'var(--gds-color-text-light)',
    iconColorFilledNeutral: 'var(--gds-color-text-light)',
    textColorHoverFilledNeutral: 'var(--gds-color-text-light)',
    textColorPressedFilledNeutral: 'var(--gds-color-text-light)',
    textColorFocusFilledNeutral: 'var(--gds-color-text-light)',
    textColorDisabledFilledNeutral: 'var(--gds-color-text-light)',
    textColorFilledPrimary: 'var(--gds-color-text-button-primary)',
    iconColorFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorHoverFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorPressedFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorFocusFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorDisabledFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorFilledInfo: 'var(--gds-color-text-light)',
    iconColorFilledInfo: 'var(--gds-color-text-light)',
    textColorHoverFilledInfo: 'var(--gds-color-text-light)',
    textColorPressedFilledInfo: 'var(--gds-color-text-light)',
    textColorFocusFilledInfo: 'var(--gds-color-text-light)',
    textColorDisabledFilledInfo: 'var(--gds-color-text-light)',
    textColorFilledSuccess: 'var(--gds-color-text-light)',
    iconColorFilledSuccess: 'var(--gds-color-text-light)',
    textColorHoverFilledSuccess: 'var(--gds-color-text-light)',
    textColorPressedFilledSuccess: 'var(--gds-color-text-light)',
    textColorFocusFilledSuccess: 'var(--gds-color-text-light)',
    textColorDisabledFilledSuccess: 'var(--gds-color-text-light)',
    textColorFilledWarning: 'var(--gds-color-text-light)',
    iconColorFilledWarning: 'var(--gds-color-text-light)',
    textColorHoverFilledWarning: 'var(--gds-color-text-light)',
    textColorPressedFilledWarning: 'var(--gds-color-text-light)',
    textColorFocusFilledWarning: 'var(--gds-color-text-light)',
    textColorDisabledFilledWarning: 'var(--gds-color-text-light)',
    textColorFilledError: 'var(--gds-color-text-button-danger-primary)',
    iconColorFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorHoverFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorPressedFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorFocusFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorDisabledFilledError: 'var(--gds-color-text-button-danger-primary)',

    // outlined text color
    textColorOutlinedPrimary: 'var(--gds-color-text-primary)',
    iconColorOutlinedPrimary: 'var(--gds-color-text-primary)',
    textColorOutlinedNeutral: 'var(--gds-color-text-button-secondary)',
    iconColorOutlinedNeutral: 'var(--gds-color-text-button-secondary)',
    textColorOutlinedInfo: 'var(--gds-color-text-info)',
    iconColorOutlinedInfo: 'var(--gds-color-text-info)',
    textColorOutlinedSuccess: 'var(--gds-color-text-success)',
    iconColorOutlinedSuccess: 'var(--gds-color-text-success)',
    textColorOutlinedError: 'var(--gds-color-text-button-danger-secondary)',
    iconColorOutlinedError: 'var(--gds-color-text-button-danger-secondary)',
    textColorOutlinedWarning: 'var(--gds-color-text-warning)',
    iconColorOutlinedWarning: 'var(--gds-color-text-warning)',

    // subtle or text text color
    textColorTertiaryPrimary: 'var(--gds-color-text-primary)',
    iconColorTertiaryPrimary: 'var(--gds-color-text-primary)',
    textColorTertiaryNeutral: 'var(--gds-color-text-button-tertiary)',
    iconColorTertiaryNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTertiaryInfo: 'var(--gds-color-text-info)',
    iconColorTertiaryInfo: 'var(--gds-color-text-info)',
    textColorTertiarySuccess: 'var(--gds-color-text-success)',
    iconColorTertiarySuccess: 'var(--gds-color-text-success)',
    textColorTertiaryError: 'var(--gds-color-text-button-danger-tertiary)',
    iconColorTertiaryError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTertiaryWarning: 'var(--gds-color-text-warning)',
    iconColorTertiaryWarning: 'var(--gds-color-text-warning)',

    // outlined
    colorOutlinedError: 'var(--gds-color-bg-button-danger-secondary)',
    colorOutlinedHoverError:
      'var(--gds-color-bg-button-danger-secondary-dark1)',
    colorOutlinedPressedError:
      'var(--gds-color-bg-button-danger-secondary-dark2)',
    colorOutlinedFocusError: 'var(--gds-color-bg-button-danger-secondary)',

    // subtle
    colorSubtleHoverError: 'var(--gds-color-bg-button-danger-tertiary-dark1)',
    colorSubtlePressedError: 'var(--gds-color-bg-button-danger-tertiary-dark2)',
    colorSubtleFocusError: 'none',

    // link & Text type text color
    iconColorText: 'var(--gds-color-text-button-tertiary)',
    textColorText: 'var(--gds-color-text-button-tertiary)',
    textColorTextHover: 'var(--gds-color-text-button-tertiary)',
    textColorTextPressed: 'var(--gds-color-text-button-tertiary)',
    textColorTextFocus: 'var(--gds-color-text-button-tertiary)',
    textColorTextDisabled: 'var(--gds-color-text-button-tertiary)',

    iconColorTextPrimary: 'var(--gds-color-text-primary)',
    textColorTextPrimary: 'var(--gds-color-text-primary)',
    textColorTextHoverPrimary: 'var(--gds-color-text-primary)',
    textColorTextPressedPrimary: 'var(--gds-color-text-primary)',
    textColorTextFocusPrimary: 'var(--gds-color-text-primary)',
    textColorTextDisabledPrimary: 'var(--gds-color-text-primary)',

    iconColorTextInfo: 'var(--gds-color-text-info)',
    textColorTextInfo: 'var(--gds-color-text-info)',
    textColorTextHoverInfo: 'var(--gds-color-text-info)',
    textColorTextPressedInfo: 'var(--gds-color-text-info)',
    textColorTextFocusInfo: 'var(--gds-color-text-info)',
    textColorTextDisabledInfo: 'var(--gds-color-text-info)',

    iconColorTextNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextHoverNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextPressedNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextFocusNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextDisabledNeutral: 'var(--gds-color-text-button-tertiary)',

    iconColorTextSuccess: 'var(--gds-color-text-success)',
    textColorTextSuccess: 'var(--gds-color-text-success)',
    textColorTextHoverSuccess: 'var(--gds-color-text-success)',
    textColorTextPressedSuccess: 'var(--gds-color-text-success)',
    textColorTextFocusSuccess: 'var(--gds-color-text-success)',
    textColorTextDisabledSuccess: 'var(--gds-color-text-success)',

    iconColorTextError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextHoverError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextPressedError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextFocusError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextDisabledError: 'var(--gds-color-text-button-danger-tertiary)',

    iconColorTextWarning: 'var(--gds-color-text-warning)',
    textColorTextWarning: 'var(--gds-color-text-warning)',
    textColorTextHoverWarning: 'var(--gds-color-text-warning)',
    textColorTextPressedWarning: 'var(--gds-color-text-warning)',
    textColorTextFocusWarning: 'var(--gds-color-text-warning)',
    textColorTextDisabledWarning: 'var(--gds-color-text-warning)',

    // other text color
    iconColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral)',
    textColorHover: 'var(--gds-color-text-button-tertiary)',
    textColorPressed: 'var(--gds-color-text-button-tertiary)',
    textColorFocus: 'var(--gds-color-text-button-tertiary)',
    textColorDisabled: 'var(--gds-color-text-button-tertiary)',

    textColorNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorHoverNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorPressedNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorFocusNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorDisabledNeutral: 'var(--gds-color-text-button-tertiary)',

    textColorTertiary: '#5E7285',

    // backgroundColor
    // primary
    colorPrimary: 'var(--gds-color-bg-button-primary)',
    colorHoverPrimary: 'var(--gds-color-bg-button-primary-dark1)',
    colorPressedPrimary: 'var(--gds-color-bg-button-primary-dark2)',
    colorFocusPrimary: 'var(--gds-color-bg-button-primary-dark2)',
    colorDisabledPrimary: 'var(--gds-color-bg-button-primary)',
    // info
    colorInfo: 'var(--gds-color-bg-info-dark1)',
    colorHoverInfo: 'var(--gds-color-bg-info)',
    colorPressedInfo: 'var(--gds-color-bg-info)',
    colorFocusInfo: 'var(--gds-color-bg-info)',
    colorDisabledInfo: 'var(--gds-color-bg-info)',
    // error
    colorError: 'var(--gds-color-bg-button-danger-primary)',
    colorHoverError: 'var(--gds-color-bg-button-danger-primary-dark1)',
    colorPressedError: 'var(--gds-color-bg-button-danger-primary-dark2)',
    colorFocusError: 'var(--gds-color-bg-button-danger-primary-dark2)',
    colorDisabledError: 'var(--gds-color-bg-button-danger-primary)',
    // success
    colorSuccess: 'var(--gds-color-text-success)',
    colorHoverSuccess: 'var(--gds-color-text-success)',
    colorPressedSuccess: 'var(--gds-color-text-success)',
    colorFocusSuccess: 'var(--gds-color-text-success)',
    colorDisabledSuccess: 'var(--gds-color-text-success)',
    // warning
    colorWarning: 'var(--gds-color-text-warning)',
    colorHoverWarning: 'var(--gds-color-text-warning)',
    colorPressedWarning: 'var(--gds-color-text-warning)',
    colorFocusWarning: 'var(--gds-color-text-warning)',
    colorDisabledWarning: 'var(--gds-color-text-warning)',

    // bg-color
    colorDefault: 'var(--gds-color-bg-button-secondary)',
    colorDisabledNeutral: 'var(--gds-color-bg-button-secondary)',
    colorFocusNeutral: 'var(--gds-color-bg-button-secondary)',
    colorHoverNeutral: 'var(--gds-color-bg-button-secondary)',
    colorPressed: 'var(--gds-color-bg-button-secondary)',
    colorPressedNeutral: 'var(--gds-color-bg-button-secondary)',
    colorQuaternaryHover: 'var(--gds-color-bg-button-secondary)',
    colorQuaternaryPressed: 'var(--gds-color-bg-button-secondary)',
    colorSecondary: 'ffffff',
    focusColor: '#2B5B88',

    linkColorActive: '#02284D',
    linkColorHover: '#1B446A',
    linkColorPressed: '#12304C',

    rippleColor: '#2B5B88',
    rippleColorError: '#BE304A',
    rippleColorNeutral: '#2B5B88',
    rippleColorPrimary: '#2B5B88',
    rippleDuration: '0s'
  },
  DataTable: {
    actionDividerColor: 'var(--gds-color-border-neutral)',
    borderColor: 'var(--gds-color-border-neutral)',
    tdColorHover: 'var(--gds-color-bg-neutral-dark2)',
    tdColorStriped: 'var(--gds-color-bg-neutral-dark1)',
    thColor: 'var(--gds-color-bg-neutral-dark2)',
    thColorHover: 'var(--gds-color-bg-neutral-dark2)',
    tdColorDisabled: 'var(--gds-color-bg-dark)',
    tdColor: 'var(--gds-color-bg-dark)',
    tdTextColor: 'var(--gds-color-text-neutral)',
    thTextColor: 'var(--gds-color-text-neutral)',
    thButtonColorHover: '#F1F2F9',
    thIconColor: 'var(--gds-color-icon-neutral)',
    thIconColorActive: 'var(--gds-color-icon-primary)',
    trBackgroundColorSelected: 'var(--gds-color-bg-info)',
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    // modal
    borderColorModal: 'var(--gds-color-border-neutral)',
    tdColorHoverModal: 'var(--gds-color-bg-neutral-dark2)',
    tdColorStripedModal: 'var(--gds-color-bg-neutral-dark1)',
    thColorModal: 'var(--gds-color-bg-neutral-dark2)',
    thColorHoverModal: 'var(--gds-color-bg-neutral-dark2)',
    tdColorModal: 'var(--gds-color-bg-dark)',
    // popover
    borderColorPopover: 'var(--gds-color-border-neutral)',
    tdColorHoverPopover: 'var(--gds-color-bg-neutral-dark2)',
    tdColorStripedPopover: 'var(--gds-color-bg-neutral-dark1)',
    thColorPopover: 'var(--gds-color-bg-neutral-dark2)',
    thColorHoverPopover: 'var(--gds-color-bg-neutral-dark2)',
    tdColorPopover: 'var(--gds-color-bg-dark)',
    expandedBackgroundColor: 'var(--gds-color-bg-neutral)',
    tableColorHover: '#F1F2F9',
    thPaddingSmall: '0.75rem 0.85rem',
    thPaddingMedium: '0.85rem 1.1rem',
    thPaddingLarge: '1rem 1.25rem',
    tdPaddingSmall: '0.75rem 0.85rem',
    tdPaddingMedium: '0.85rem 1.1rem',
    tdPaddingLarge: '1rem 1.25rem',
    sorterSize: '24px'
  },
  Table: {
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)'
  },
  Empty: {
    titleTextColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    actionsTextColor: 'var(--gds-color-text-neutral-light1)',
    iconColor: 'var(--gds-color-icon-neutral)',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    fontSizeXLarge: 'var(--gds-font-size-18)',
    titleFontSizeSmall: 'var(--gds-font-size-14)',
    titleFontSizeMedium: 'var(--gds-font-size-16)',
    titleFontSizeLarge: 'var(--gds-font-size-18)',
    titleFontSizeXLarge: 'var(--gds-font-size-22)',
    descriptionFontSizeSmall: 'var(--gds-font-size-12)',
    descriptionFontSizeMedium: 'var(--gds-font-size-14)',
    descriptionFontSizeLarge: 'var(--gds-font-size-16)',
    descriptionFontSizeXLarge: 'var(--gds-font-size-14)'
  },
  Result: {
    lineHeight: 'var(--gds-line-height16)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    iconColorError: 'var(--gds-color-icon-danger)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorWarning: 'var(--gds-color-icon-warning)'
  },
  Typography: {
    textColorInherit: 'inherit',
    fontHeading1Sb: 'var(--gds-font-heading-1-sb)',
    fontHeading2Sb: 'var(--gds-font-heading-2-sb)',
    fontHeading3M: 'var(--gds-font-heading-3-m)',
    fontHeading4R: 'var(--gds-font-heading-4-r)',
    fontHeading4M: 'var(--gds-font-heading-4-m)',
    fontHeading5M: 'var(--gds-font-heading-5-m)',
    fontHeading6R: 'var(--gds-font-heading-6-r)',
    fontHeading6M: 'var(--gds-font-heading-6-m)',

    letterSpacingHeading1Sb: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading2Sb: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading3M: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading4R: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading4M: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading5M: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading6R: 'var(--gds-letter-spacing-1)',
    letterSpacingHeading6M: 'var(--gds-letter-spacing-2)',

    fontParagraph1R: 'var(--gds-font-paragraph-1-r)',
    fontParagraph1M: 'var(--gds-font-paragraph-1-m)',
    fontParagraph2R: 'var(--gds-font-paragraph-2-r)',
    fontParagraph2M: 'var(--gds-font-paragraph-2-m)',
    fontParagraph3R: 'var(--gds-font-paragraph-3-r)',
    fontParagraph3M: 'var(--gds-font-paragraph-3-m)',

    fontCode1R: 'var(--gds-font-code-1-r)',

    fontBody1R: 'var(--gds-font-body-1-r)',
    fontBody1M: 'var(--gds-font-body-1-m)',
    fontBody2R: 'var(--gds-font-body-2-r)',
    fontBody2M: 'var(--gds-font-body-2-m)',
    fontBody3R: 'var(--gds-font-body-3-r)',
    fontBody3M: 'var(--gds-font-body-3-m)',
    fontBody4R: 'var(--gds-font-body-4-r)',
    fontBody4M: 'var(--gds-font-body-4-m)',
    fontBody5M: 'var(--gds-font-body-5-m)',
    fontBody5R: 'var(--gds-font-body-5-r)',

    fontLabel1R: 'var(--gds-font-label-1-r)',
    fontLabel1M: 'var(--gds-font-label-1-m)',
    fontLabel2R: 'var(--gds-font-label-2-r)',
    fontLabel2M: 'var(--gds-font-label-2-m)',

    fontLink1R: 'var(--gds-font-link-1-r)',
    fontLink1M: 'var(--gds-font-link-1-m)',
    fontLink2R: 'var(--gds-font-link-2-r)',
    fontLink2M: 'var(--gds-font-link-2-m)',
    fontLink3R: 'var(--gds-font-link-3-r)',
    fontLink3M: 'var(--gds-font-link-3-m)',

    aTextColor: 'var(--gds-color-text-info)',
    headingFontSize1: 'var(--gds-font-size-32)',
    headingFontSize2: 'var(--gds-font-size-24)',
    headingFontSize3: 'var(--gds-font-size-20)',
    headingFontSize4: 'var(--gds-font-size-18)',
    headingFontSize5: 'var(--gds-font-size-16)',
    headingFontSize6: 'var(--gds-font-size-14)',
    headingLineHeight: '1.2',
    liLineHeight: '1.6',
    liFontSize: 'var(--gds-font-size-14)',
    headerFontWeight: 500,
    blockquoteLineHeight: '1.6',
    blockquoteFontSize: 'var(--gds-font-size-14)',
    codeBorderRadius: '2px',
    pLineHeight: '1.6',
    pFontSize: 'var(--gds-font-size-14)',
    labelTextColor: 'var(--gds-color-text-neutral)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    blockquoteTextColor: 'var(--gds-color-text-neutral)',
    blockquotePrefixColor: 'var(--gds-color-border-neutral)',
    liTextColor: 'var(--gds-color-text-neutral)',
    hrColor: 'var(--gds-color-border-neutral)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    pTextColor: 'var(--gds-color-text-neutral)',
    pTextColor1Depth: 'var(--gds-color-text-neutral)',
    pTextColor2Depth: 'var(--gds-color-text-neutral)',
    pTextColor3Depth: 'var(--gds-color-text-neutral)',
    headingBarColor: 'var(--gds-color-bg-primary)',
    headingBarColorPrimary: 'var(--gds-color-bg-primary)',
    headingBarColorInfo: 'var(--gds-color-bg-info)',
    headingBarColorError: 'var(--gds-color-bg-danger)',
    headingBarColorWarning: 'var(--gds-color-bg-warning)',
    headingBarColorSuccess: 'var(--gds-color-bg-success)',
    textColor: 'var(--gds-color-text-neutral)',
    textColor1Depth: 'var(--gds-color-text-neutral)',
    textColor2Depth: 'var(--gds-color-text-neutral)',
    textColor3Depth: 'var(--gds-color-text-neutral)',
    textColorPrimary: 'var(--gds-color-text-primary)',
    textColorInfo: 'var(--gds-color-text-info)',
    textColorSuccess: 'var(--gds-color-text-success)',
    textColorWarning: 'var(--gds-color-text-warning)',
    textColorError: 'var(--gds-color-text-danger)',
    codeTextColor: 'var(--gds-color-text-neutral)',
    codeColor: 'var(--gds-color-bg-neutral-light)',
    opacity1: '0.82',
    opacity2: '0.72',
    opacity3: '0.38',
    opacity4: '0.24',
    opacity5: '0.18',
    codeBorder: '1px solid var(--gds-color-border-neutral)'
  },
  DatePicker: {
    itemFontSize: 'var(--gds-font-size-14)',
    calendarDaysFontSize: 'var(--gds-font-size-14)',
    calendarTitleFontSize: 'var(--gds-font-size-14)',
    itemTextColor: 'var(--gds-color-text-neutral)',
    itemTextColorDisabled: 'var(--gds-color-text-neutral-light3)',
    itemTextColorActive: 'var(--gds-color-text-light)',
    itemTextColorCurrent: 'var(--gds-color-text-primary)',
    itemColorIncluded: 'var(--gds-color-bg-primary-light1)',
    itemColorHover: 'var(--gds-color-bg-primary-light1)',
    itemColorDisabled: 'var(--gds-color-bg-primary-light1)',
    itemColorActive: 'var(--gds-color-text-primary)',
    itemBorderRadius: 'var(--gds-border-radius-xs)',
    panelColor: 'var(--gds-color-bg-neutral-dark2)',
    panelTextColor: 'var(--gds-color-text-neutral)',
    arrowColor: 'var(--gds-color-icon-neutral)',
    calendarTitleTextColor: 'var(--gds-color-text-neutral)',
    calendarTitleColorHover: 'var(--gds-color-bg-primary-light1)',
    calendarDaysTextColor: 'var(--gds-color-text-neutral-light1)',
    panelHeaderDividerColor: 'var(--gds-color-border-neutral)',
    calendarDaysDividerColor: 'var(--gds-color-border-neutral)',
    calendarDividerColor: 'var(--gds-color-border-neutral)',
    panelActionDividerColor: 'var(--gds-color-border-neutral)',
    panelBorderRadius: 'var(--gds-border-radius-xs)',
    calendarTitleFontWeight: 500,
    scrollItemBorderRadius: 'var(--gds-border-radius-xs)',
    shortcutItemColor: 'var(--gds-color-text-neutral-light1)',
    shortcutItemHoverColor: 'var(--gds-color-text-neutral)',
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorDisabled: 'var(--gds-color-icon-neutral-light)'
  },
  InternalSelection: {
    paddingSingle: '0 36px 0px 8px',
    paddingMultiple: '3px 36px 3px 8px',
    textColor: 'var(--gds-color-bg-dark)',
    color: 'var(--gds-color-bg-base)'
  },
  Input: {
    heightXSmall: '22px',
    heightSmall: '28px',
    heightMedium: '34px',
    heightLarge: '40px',
    fontSizeXSmall: 'var(--gds-font-size-12)',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    lineHeight: '1.6',
    borderRadius: 'var(--gds-border-radius-xs)',
    iconSize: '16px',
    lineHeightTextarea: '1rem',
    countTextColorDisabled: 'var(--gds-color-text-neutral-light3)',
    countTextColor: 'var(--gds-color-text-neutral-light3)',
    groupLabelColor: 'var(--gds-color-text-neutral-light1)',
    groupLabelTextColor: 'var(--gds-color-text-neutral-light2)',
    textColor: 'var(--gds-color-text-neutral)',
    textColorDisabled: 'var(--gds-color-text-neutral-light2)',
    textDecorationColor: 'var(--gds-color-text-neutral-light2)',
    caretColor: 'var(--gds-color-text-primary)',
    placeholderColor: 'var(--gds-color-text-neutral3)',
    placeholderColorDisabled: 'var(--gds-color-text-neutral3)',
    color: 'var(--gds-color-bg-neutral)',
    colorDisabled: 'var(--gds-color-bg-neutral)',
    colorFocus: 'var(--gds-color-border-primary-light)',
    backgroundColor: 'var(--gds-color-bg-neutral)',
    inputPrefixBackgroudColor: 'var(--gds-color-bg-neutral-dark2)',
    borderHover: 'var(--gds-color-border-neutral-dark1)',
    borderDisabled: 'var(--gds-color-border-neutral)',
    loadingColor: 'var(--gds-color-border-primary)',
    groupLabelBorder: '1px solid var(--gds-color-border-neutral-dark3)',
    border: '1px solid var(--gds-color-border-neutral-dark3)',
    borderFocus: '1px solid var(--gds-color-border-primary)',
    boxShadowFocus: '0 1px var(--gds-color-border-primary)',
    // warning
    loadingColorWarning: 'var(--gds-color-border-warning-dark)',
    colorFocusWarning: 'var(--gds-color-bg-light)',
    caretColorWarning: 'var(--gds-color-icon-warning)',
    borderWarning: '1px solid var(--gds-color-border-warning)',
    borderHoverWarning: '1px solid var(--gds-color-border-warning-dark)',
    borderFocusWarning: '1px solid var(--gds-color-border-warning-dark)',
    boxShadowFocusWarning: '0 1px var(--gds-color-border-warning)',
    // error
    loadingColorError: 'var(--gds-color-border-danger-dark)',
    colorFocusError: 'var(--gds-color-bg-light)',
    caretColorError: 'var(--gds-color-icon-danger)',
    clearColor: 'var(--gds-color-icon-neutral)',
    clearColorHover: 'var(--gds-color-icon-neutral-dark1)',
    clearColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorDisabled: 'var(--gds-color-icon-neutral)',
    iconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    iconColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    suffixTextColor: 'var(--gds-color-text-neutral2)',
    borderHoverError: '1px solid var(--gds-color-border-danger-dark)',
    borderFocusError: '1px solid var(--gds-color-border-danger-dark)',
    boxShadowFocusError: '0 1px var(--gds-color-border-danger)',
    borderError: '1px solid var(--gds-color-border-danger)'
  },
  Stepper: {
    indicatorIconColorProcess: 'var(--gds-color-icon-neutral-dark1)',
    indicatorIconColorWait: 'var(--gds-color-icon-neutral-light)',
    indicatorIconColorFinish: 'var(--gds-color-icon-success)',
    indicatorIconColorError: 'var(--gds-color-icon-danger)',
    indicatorTextColorProcess: 'var(--gds-color-text-light)',
    indicatorTextColorWait: 'var(--gds-color-text-neutral-light3)',
    indicatorTextColorFinish: 'var(--gds-color-text-success)',
    indicatorTextColorError: 'var(--gds-color-text-danger)',
    indicatorBorderColorProcess: 'var(--gds-color-border-primary)',
    indicatorBorderColorWait: 'var(--gds-color-border-neutral-dark2)',
    indicatorBorderColorFinish: 'var(--gds-color-border-success)',
    indicatorBorderColorError: 'var(--gds-color-border-danger)',
    hoverIndicatorBorderColorProcess: 'var(--gds-color-border-primary)',
    hoverIndicatorBorderColorWait: 'var(--gds-color-border-neutral-dark2)',
    hoverIndicatorBorderColorFinish: 'var(--gds-color-border-success)',
    hoverIndicatorBorderColorError: 'var(--gds-color-border-danger)',
    indicatorColorProcess: 'var(--gds-color-bg-primary-dark2)',
    indicatorColorWait: 'var(--gds-color-bg-primary-dark2)',
    indicatorColorFinish: 'var(--gds-color-bg-success)',
    indicatorColorError: 'var(--gds-color-bg-danger)',
    splitorColorProcess: 'var(--gds-color-border-neutral-dark2)',
    splitorColorWait: 'var(--gds-color-border-neutral-dark2)',
    splitorColorFinish: 'var(--gds-color-border-success)',
    splitorColorError: 'var(--gds-color-border-danger)',
    hoverTextColorProcess: 'var(--gds-color-text-neutral-light2)',
    hoverTextColorWait: 'var(--gds-color-text-neutral-light3)',
    hoverTextColorFinish: 'var(--gds-color-text-neutral)',
    hoverTextColorError: 'var(--gds-color-text-danger)',
    hoverDescriptionColorProcess: 'var(--gds-color-text-neutral-light2)',
    hoverDescriptionColorWait: 'var(--gds-color-text-neutral-light3)',
    hoverDescriptionColorFinish: 'var(--gds-color-text-neutral)',
    hoverDescriptionColorError: 'var(--gds-color-text-danger)',
    hoverIndicatorColorProcess: 'var(--gds-color-bg-primary-dark2)',
    hoverIndicatorColorWait: 'var(--gds-color-bg-primary-dark2)',
    hoverIndicatorColorFinish: 'var(--gds-color-bg-success)',
    hoverIndicatorColorError: 'var(--gds-color-bg-danger)',
    headerTextColorProcess: 'var(--gds-color-text-neutral)',
    headerTextColorWait: 'var(--gds-color-text-neutral-light3)',
    headerTextColorFinish: 'var(--gds-color-text-neutral)',
    headerTextColorError: 'var(--gds-color-text-danger)',
    descriptionTextColorProcess: 'var(--gds-color-text-neutral-light2)',
    descriptionTextColorWait: 'var(--gds-color-text-neutral-light3)',
    descriptionTextColorFinish: 'var(--gds-color-text-neutral)',
    descriptionTextColorError: 'var(--gds-color-text-danger)'
  },
  Panel: {
    textColor: 'var(--gds-color-text-neutral-light2)',
    dividerColor: 'var(--gds-color-border-neutral)',
    headerTextColor: 'var(--gds-color-text-neutral-light1)',
    baseColor: 'var(--gds-color-bg-dark)'
  },
  Link: {
    color: 'var(--gds-color-text-info)',
    colorDefault: 'var(--gds-color-text-info)',
    colorActive: 'var(--gds-color-text-info-dark2)',
    colorVisited: 'var(--gds-color-text-support-violet-light)',
    colorHover: 'var(--gds-color-text-info-dark1)',
    colorFocus: 'var(--gds-color-border-primary-light)',
    fontSize: 'var(--gds-font-size-14)',
    lineHeight: 'var(--gds-line-height-16)',
    fontWeight: 500
  },
  Menu: {
    borderRadius: 'var(--gds-border-radius-xs)',
    itemColorActive: 'var(--gds-color-bg-neutral)',
    itemColorActiveHover: 'var(--gds-color-bg-neutral-light1)',
    itemColorActiveCollapsed: 'var(--gds-color-bg-neutral-light1)',
    color: 'var(--gds-color-bg-dark)',
    groupTextColor: 'var(--gds-color-text-neutral-light2)',
    itemColorHover: 'var(--gds-color-bg-neutral-light1)',
    itemTextColor: 'var(--gds-color-text-neutral-light1)',
    itemTextColorHover: 'var(--gds-color-text-neutral-light1)',
    itemTextColorActive: 'var(--gds-color-text-primary)',
    itemTextColorActiveHover: 'var(--gds-color-text-primary)',
    itemTextColorChildActive: 'var(--gds-color-text-primary)',
    itemTextColorChildActiveHover: 'var(--gds-color-text-primary)',
    itemIconColor: 'var(--gds-color-icon-neutral)',
    itemIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    itemIconColorActive: 'var(--gds-color-icon-primary)',
    itemIconColorActiveHover: 'var(--gds-color-icon-primary)',
    itemIconColorChildActive: 'var(--gds-color-icon-primary)',
    itemIconColorChildActiveHover: 'var(--gds-color-icon-primary)',
    itemIconColorCollapsed: 'var(--gds-color-icon-neutral)',
    colorInverted: 'var(--gds-color-bg-nav-dark)',
    itemHeight: '40px',
    fontSize: 'var(--gds-font-size-14)',
    // createHorizontalVars('#BBB', '#FFF', vars),

    itemHorizontalHeight: '32px',
    borderColorHorizontal: 'var(--gds-color-border-neutral)',
    // for inverted
    arrowColorInverted: 'var(--gds-color-icon-neutral-light)',
    arrowColorHoverInverted: 'var(--gds-color-icon-neutral-light)',
    arrowColorActiveInverted: 'var(--gds-color-icon-neutral-light)',
    arrowColorActiveHoverInverted: 'var(--gds-color-icon-neutral-light)',
    arrowColorChildActiveHoverInverted: 'var(--gds-color-icon-neutral-light)',
    arrowColorChildActiveInverted: 'var(--gds-color-icon-neutral-light)',
    itemTextColorHorizontalInverted: 'var(--gds-color-text-inverse)',
    itemTextColorHoverHorizontalInverted: 'var(--gds-color-text-inverse)',
    itemTextColorChildActiveHorizontalInverted: 'var(--gds-color-text-light)',
    itemTextColorChildActiveHoverHorizontalInverted:
      'var(--gds-color-text-light)',
    itemTextColorActiveHorizontalInverted: 'var(--gds-color-text-light)',
    itemTextColorActiveHoverHorizontalInverted: 'var(--gds-color-text-light)',
    itemIconColorHorizontalInverted: 'var(--gds-color-icon-neutral-light)',
    itemIconColorHoverHorizontalInverted: 'var(--gds-color-icon-neutral-light)',
    itemIconColorActiveHorizontalInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorActiveHoverHorizontalInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorChildActiveHorizontalInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorChildActiveHoverHorizontalInverted:
      'var(--gds-color-icon-inverse)',
    itemHoverHorizontalInverted: 'var(--gds-color-bg-neutral-dark1)',
    itemSelectedHorizontalInverted: 'var(--gds-color-bg-neutral-light)',
    itemHoverActiveHorizontalInverted: 'var(--gds-color-bg-neutral-dark2)',
    // for non-inverted
    arrowColor: 'var(--gds-color-icon-neutral)',
    arrowColorHover: 'var(--gds-color-icon-neutral)',
    arrowColorActive: 'var(--gds-color-icon-neutral)',
    arrowColorActiveHover: 'var(--gds-color-icon-neutral)',
    arrowColorChildActiveHover: 'var(--gds-color-icon-neutral)',
    arrowColorChildActive: 'var(--gds-color-icon-neutral)',
    itemTextColorHorizontal: 'var(--gds-color-text-neutral)',
    itemTextColorHoverHorizontal: 'var(--gds-color-text-neutral)',
    itemTextColorActiveHorizontal: 'var(--gds-color-text-primary)',
    itemTextColorActiveHoverHorizontal: 'var(--gds-color-text-primary)',
    itemTextColorChildActiveHorizontal: 'var(--gds-color-text-primary)',
    itemTextColorChildActiveHoverHorizontal: 'var(--gds-color-text-primary)',
    itemIconColorHorizontal: 'var(--gds-color-icon-neutral)',
    itemIconColorHoverHorizontal: 'var(--gds-color-icon-neutral)',
    itemIconColorActiveHorizontal: 'var(--gds-color-icon-neutral)',
    itemIconColorActiveHoverHorizontal: 'var(--gds-color-icon-primary)',
    itemIconColorChildActiveHorizontal: 'var(--gds-color-icon-primary)',
    itemIconColorChildActiveHoverHorizontal: 'var(--gds-color-icon-primary)',
    itemHoverHorizontal: 'var(--gds-color-bg-neutral)',
    itemSelectedHorizontal: 'var(--gds-color-bg-neutral-light)',
    itemHoverActiveHorizontal: 'var(--gds-color-bg-neutral-dark1)',

    // createPartialInvertedVars('#BBB', primaryColor, '#FFF', '#AAA')
    itemColorHoverInverted: 'var(--gds-color-bg-nav-dark-light1)',
    itemColorActiveInverted: 'var(--gds-color-bg-nav-dark-light2)',
    itemColorActiveHoverInverted: 'var(--gds-color-bg-nav-dark-light1)',
    itemColorActiveCollapsedInverted: 'var(--gds-color-bg-nav-dark-light1)',
    itemTextColorInverted: 'var(--gds-color-text-inverse)',
    itemTextColorHoverInverted: 'var(--gds-color-text-inverse)',
    itemTextColorChildActiveInverted: 'var(--gds-color-text-light)',
    itemTextColorChildActiveHoverInverted: 'var(--gds-color-text-light)',
    itemTextColorActiveInverted: 'var(--gds-color-text-light)',
    itemTextColorActiveHoverInverted: 'var(--gds-color-text-light)',
    itemIconColorInverted: 'var(--gds-color-icon-neutral-light)',
    itemIconColorHoverInverted: 'var(--gds-color-icon-neutral-light)',
    itemIconColorActiveInverted: 'var(--gds-color-bg-nav-dark)',
    itemIconColorActiveHoverInverted: 'var(--gds-color-bg-nav-dark)',
    itemIconColorChildActiveInverted: 'var(--gds-color-bg-nav-dark)',
    itemIconColorChildActiveHoverInverted: 'var(--gds-color-bg-nav-dark)',
    itemIconColorCollapsedInverted: 'var(--gds-color-icon-neutral-light)',
    groupTextColorInverted: 'var(--gds-color-text-neutral-light3)',
    dividerColorInverted: 'var(--gds-color-border-nav-dark)'
  },
  Progress: {
    fontSize: 'var(--gds-font-size-14)',
    fontSizeCircle: 'var(--gds-font-size-28)',
    fontWeightCircle: 400,
    railHeight: '8px',
    iconSizeCircle: '36px',
    iconSizeLine: '18px',
    iconColorPrimary: 'var(--gds-color-icon-primary)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    iconColorError: 'var(--gds-color-icon-danger)',
    textColorCircle: 'var(--gds-color-text-neutral)',
    textColorLineInner: 'var(--gds-color-text-neutral)',
    textColorLineOuter: 'var(--gds-color-text-neutral)',
    fillColorPrimary: 'var(--gds-color-bg-primary)',
    fillColorInfo: 'var(--gds-color-bg-info-dark1)',
    fillColorSuccess: 'var(--gds-color-bg-success)',
    fillColorWarning: 'var(--gds-color-bg-warning)',
    fillColorError: 'var(--gds-color-bg-danger)',
    lineBgProcessing:
      'linear-gradient(90deg, var(--gds-color-bg-neutral) 0%, var(--gds-color-bg-neutral-dark2) 100%)'
  },
  Tooltip: {
    fontSize: 'var(--gds-font-size-12)',
    borderRadius: 'var(--gds-border-radius-xs)',
    bgColor: 'var(--gds-color-bg-neutral-dark5)',
    textColor: 'var(--gds-color-text-light)',
    padding: '0.25rem 0.5rem',
    space: '0.375rem',
    spaceArrow: '0.75rem',
    arrowOffset: '0.75rem',
    arrowOffsetVertical: '0.75rem',
    arrowHeight: '0.5rem'
  },
  Tree: {
    nodeColorHover: 'var(--gds-color-bg-neutral-dark1)',
    nodeColorPressed: 'var(--gds-color-bg-primary-light1)',
    nodeColorActive: 'var(--gds-color-bg-primary-light1)',
    arrowColor: 'var(--gds-color-icon-neutral-dark1)',
    nodeTextColor: 'var(--gds-color-text-neutral)',
    nodeTextColorActive: 'var(--gds-color-text-primary)',
    nodeTextColorHover: 'var(--gds-color-text-neutral)',
    loadingColor: 'var(--gds-color-icon-primary)',
    dropMarkColor: 'var(--gds-color-border-primary)',
    dividerColor: 'var(--gds-color-border-neutral)',
    nodeTextColorDisabled: 'var(--gds-color-text-neutral)',
    nodeBorderRadius: 'var(--gds-border-radius-xs)',
    nodeHighlightBottomColor: 'transparent',
    lineWidth: '2px',
    nodeWrapperPadding: '0px',
    nodePadding: '5px 0',
    nodeHeight: '30px',
    fontSizeXSmall: 'var(--gds-font-size-12)',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    fontSizeXLarge: 'var(--gds-font-size-16)',
    lineHeight: '1.5'
  },
  Scrollbar: {
    scrollBoxShadowColor: 'rgba(2, 13, 75, 0.1)'
  },
  Spinner: {
    fontSize: 'var(--gds-font-size-14)',
    invertedTextColor: 'var(--gds-color-text-inverse)',
    invertedColor: 'var(--gds-color-bg-light)',
    invertedSecondaryColor: 'var(--gds-color-bg-neutral-dark4)',
    textColor: 'var(--gds-color-text-neutral)',
    color: 'var(--gds-color-bg-primary)',
    secondaryColor: 'var(--gds-color-bg-neutral-dark2)',
    sizeXSmall: '22px',
    sizeSmall: '28px',
    sizeMedium: '34px',
    sizeLarge: '40px',
    sizeXLarge: '46px',
    opacitySpinning: '1'
  },
  Tabs: {
    tabFontSizeCard: 'var(--gds-font-size-14)',
    colorSegment: 'var(--gds-color-bg-neutral)',
    // Line
    tabTextColorLine: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveLine: 'var(--gds-color-border-primary)',
    tabTextColorHoverLine: 'var(--gds-color-text-neutral-light1)',
    tabTextColorDisabledLine: 'var(--gds-color-text-neutral-light2)',
    // Segment
    tabTextColorSegment: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveSegment: 'var(--gds-color-text-primary)',
    tabTextColorHoverSegment: 'var(--gds-color-text-neutral-light1)',
    tabTextColorDisabledSegment: 'var(--gds-color-text-neutral-light1)',
    // Bar
    tabTextColorBar: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveBar: 'var(--gds-color-text-primary)',
    tabTextColorHoverBar: 'var(--gds-color-text-neutral-light1)',
    tabTextColorDisabledBar: 'var(--gds-color-text-neutral-light1)',
    // Card
    tabTextColorCard: 'var(--gds-color-text-neutral-light2)',
    tabTextColorHoverCard: 'var(--gds-color-text-neutral-light1)',
    tabTextColorActiveCard: 'var(--gds-color-text-primary)',
    tabTextColorDisabledCard: 'var(--gds-color-text-neutral-light1)',
    barColor: 'var(--gds-color-bg-tab-primary)',
    closeIconColor: 'var(--gds-color-icon-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral)',
    closeColorHover: 'var(--gds-color-bg-neutral)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark1)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    tabColorSegment: 'var(--gds-color-bg-neutral-dark3)',
    tabBorderColor: 'var(--gds-color-border-neutral-dark1)',
    paneTextColor: 'var(--gds-color-text-neutral-light1)',
    tabFontWeightActive: 500,
    tabFontWeight: 400,
    tabBorderRadius: 'var(--gds-border-radius-xs)',
    tabColor: 'var(--gds-color-text-primary)',
    fontWeightStrong: 500,
    thPaddingSmall: '0.75rem 0.85rem',
    thPaddingMedium: '0.85rem 1.1rem',
    thPaddingLarge: '1rem 1.25rem',
    tdPaddingSmall: '0.75rem 0.85rem',
    tdPaddingMedium: '0.85rem 1.1rem',
    tdPaddingLarge: '1rem 1.25rem',
    sorterSize: '24px'
  },
  JsonViewer: {
    fontSizeXLarge: 'var(--gds-font-size-16)',
    fontWeightStrong: 500,
    fontSize: 'var(--gds-font-size-14)',
    borderRadius: 'var(--gds-border-radius-m)',
    lineNumberTextColor: 'var(--gds-color-text-neutral-light2)',
    copyIconColor: 'var(--gds-color-icon-neutral-dark1)',
    chevronIconColor: 'var(--gds-color-icon-neutral)',
    backgroundColor: 'var(--gds-color-bg-neutral-light)',
    lineNumberbackgroundColor: 'var(--gds-color-bg-neutral-dark1)',
    bracketColor: 'var(--gds-color-text-neutral)',
    keyColor: 'var(--gds-color-text-support-violet-light)',
    numberValueColor: 'var(--gds-color-text-warning)',
    stringValueColor: 'var(--gds-color-text-success)',
    nullvalueColor: 'var(--gds-color-text-neutral-light2)',
    booleanValueColor: 'var(--gds-color-text-primary)',
    undefinedValueColor: 'var(--gds-color-text-neutral-light2)',
    scrollbarColor: 'var(--gds-color-bg-neutral-dark2)',
    commentColor: 'var(--gds-color-text-warning)',
    optionColor: 'var(--gds-color-text-primary)'
  },
  Notification: {
    titleFontSize: 'var(--gds-font-size-14)',
    metaFontSize: 'var(--gds-font-size-12)',
    descriptionFontSize: 'var(--gds-font-size-12)',
    lineHeight: '1.6',
    borderRadius: 'var(--gds-border-radius-xs)',
    fontSize: 'var(--gds-font-size-14)',
    headerFontWeight: 500,
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    color: 'var(--gds-color-bg-dark2)',
    colorSuccess: 'var(--gds-color-bg-success)',
    colorInfo: 'var(--gds-color-bg-info)',
    colorWarning: 'var(--gds-color-bg-warning)',
    colorError: 'var(--gds-color-bg-danger)',
    iconColorError: 'var(--gds-color-icon-danger)',
    textColor: 'var(--gds-color-text-neutral)',
    closeIconColor: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    closeColorHover: 'var(--gds-color-bg-neutral)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    descriptionTextColor: 'var(--gds-color-text-neutral-light1)',
    actionTextColor: 'var(--gds-color-text-neutral)'
  },
  Accordion: {
    fontSize: 'var(--gds-font-size-14)',
    titleFontSize: 'var(--gds-font-size-16)',
    dividerColor: 'var(--gds-color-border-neutral)',
    textColor: 'var(--gds-color-text-neutral)',
    contentColor: 'var(--gds-color-text-neutral-light1)',
    arrowColor: 'var(--gds-color-icon-neutral)',
    arrowActiveColor: 'var(--gds-color-icon-neutral-dark1)',
    boxedBgColor: 'var(--gds-color-bg-neutral)',
    arrowBgColor: 'transparent',
    hoverColor: 'var(--gds-color-bg-neutral)',
    activeColor: 'var(--gds-color-bg-neutral)',
    disabledOpacity: '0.4'
  },
  PageHeader: {
    fontSize: 'var(--gds-font-size-14)',
    titleTextColorInverted: 'var(--gds-color-text-light)',
    backColorInverted: 'var(--gds-color-icon-inverse)',
    backColorHoverInverted: 'var(--gds-color-icon-inverse-dark1)',
    backColorPressedInverted: 'var(--gds-color-icon-inverse-dark2)',
    descriptionTextColorInverted: 'var(--gds-color-text-inverse)',
    titleFontWeight: 500,
    titleTextColor: 'var(--gds-color-text-neutral)',
    backColor: 'var(--gds-color-icon-neutral)',
    backColorHover: 'var(--gds-color-icon-neutral-dark1)',
    backColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    descriptionTextColor: 'var(--gds-color-text-neutral-light2)'
  },
  Pagination: {
    itemSizeSmall: '22px',
    itemSizeMedium: '36px',
    itemSizeLarge: '34px',
    buttonColor: 'var(--gds-color-bg-button-secondary)',
    buttonColorHover: 'var(--gds-color-bg-button-secondary-dark1)',
    buttonColorPressed: 'var(--gds-color-bg-button-secondary-dark2)',
    buttonIconColor: 'var(--gds-color-icon-neutral-dark1)',
    buttonIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    buttonIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    itemTextColor: 'var(--gds-color-text-neutral)',
    itemTextColorHover: 'var(--gds-color-text-neutral)',
    itemTextColorPressed: 'var(--gds-color-text-neutral)',
    itemTextColorActive: 'var(--gds-color-text-neutral)',
    itemTextColorDisabled: 'var(--gds-color-text-neutral-light3)',
    itemColor: 'var(--gds-color-text-neutral)',
    itemColorHover: 'var(--gds-color-border-neutral)',
    itemColorPressed: 'var(--gds-color-border-neutral)',
    itemColorActive: 'var(--gds-color-border-neutral)',
    itemColorActiveHover: 'var(--gds-color-border-neutral)',
    itemColorDisabled: 'var(--gds-color-text-neutral)',
    itemBorderRadius: 'var(--gds-border-radius-xs)',
    itemFontSizeSmall: 'var(--gds-font-size-12)',
    itemFontSizeMedium: 'var(--gds-font-size-14)',
    itemFontSizeLarge: 'var(--gds-font-size-14)',
    jumperFontSizeSmall: 'var(--gds-font-size-12)',
    jumperFontSizeMedium: 'var(--gds-font-size-14)',
    jumperFontSizeLarge: 'var(--gds-font-size-14)',
    jumperTextColor: 'var(--gds-color-text-neutral-light1)',
    jumperTextColorDisabled: 'var(--gds-color-text-neutral-light1)',
    clearColor: 'var(--gds-color-icon-neutral)',
    clearColorHover: 'var(--gds-color-icon-neutral-dark1)',
    clearColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    arrowColor: 'var(--gds-color-icon-neutral-dark1)',
    buttonBorder: '1px solid var(--gds-color-border-button-secondary)',
    buttonBorderHover:
      '1px solid var(--gds-color-border-button-secondary-dark1)',
    buttonBorderPressed:
      '1px solid var(--gds-color-border-button-secondary-dark2)',
    itemBorderActive: '1px solid var(--gds-color-border-primary)',
    itemBorderDisabled: '1px solid var(--gds-color-border-primary)',
    itemBorder: '1px solid var(--gds-color-border-neutral)',
    itemBorderHover: '1px solid var(--gds-color-border-neutral)',
    itemBorderPressed: '1px solid var(--gds-color-border-neutral)'
  },
  Breadcrumb: {
    itemTextColor: 'var(--gds-color-text-info)',
    itemTextColorHover: 'var(--gds-color-text-info-dark1)',
    itemTextColorPressed: 'var(--gds-color-text-info-dark2)',
    itemTextColorActive: 'var(--gds-color-text-neutral)',
    itemColorHover: 'transparent',
    itemColorPressed: 'transparent',
    separatorColor: 'var(--gds-color-icon-neutral)',
    separatorPadding: '0 4px',
    padding: '2px 0',
    itemLineHeight: 'var(--gds-line-height-16)'
  },
  Alert: {
    color: 'var(--gds-color-bg-dark)',
    borderInfo: '1px solid var(--gds-color-border-info)',
    colorInfo: 'var(--gds-color-bg-info)',
    titleTextColorInfo: 'var(--gds-color-text-neutral)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    contentTextColorInfo: 'var(--gds-color-text-neutral-light2)',
    closeIconColorInfo: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHoverInfo: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressedInfo: 'var(--gds-color-icon-neutral-dark1)',
    borderSuccess: '1px solid var(--gds-color-border-success)',
    colorSuccess: 'var(--gds-color-bg-success)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    borderWarning: '1px solid var(--gds-color-border-warning)',
    colorWarning: 'var(--gds-color-bg-warning)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    borderError: '1px solid var(--gds-color-border-danger)',
    colorError: 'var(--gds-color-bg-danger)',
    iconColorError: 'var(--gds-color-icon-danger)'
  },
  Tag: {
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    heightXSmall: '16px',
    heightSmall: 'var(--gds-line-height-20)',
    heightMedium: 'var(--gds-line-height-24)',
    heightLarge: 'var(--gds-line-height-28)',
    borderRadius: 'var(--gds-border-radius-xs)',
    opacityDisabled: '0.4',
    fontSizeXSmall: 'var(--gds-font-size-12)',
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-14)',
    fontWeightStrong: 500,
    // checked
    borderChecked: '1px solid var(--gds-color-border-primary)',
    // focus
    borderFocused: 'var(--gds-color-border-primary-light)',
    // default
    textColorNeutral: 'var(--gds-color-text-neutral)',
    textColorNeutralChecked: 'var(--gds-color-text-neutral-light1)',
    textColorNeutralUnchecked: 'var(--gds-color-text-neutral-light1)',
    colorNeutral: 'var(--gds-color-bg-neutral)',
    iconColorNeutral: 'var(--gds-color-icon-neutral)',
    iconColorNeutralChecked: 'var(--gds-color-icon-neutral)',
    colorBorderedNeutral: 'var(--gds-color-border-neutral-light2)',
    colorHoverNeutral: 'var(--gds-color-bg-neutral-dark2)',
    colorPressedNeutral: 'var(--gds-color-bg-neutral-dark3)',
    colorCheckedNeutral: 'var(--gds-color-bg-neutral)',
    closeIconColorNeutral: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverNeutral: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedNeutral: 'var(--gds-color-icon-neutral)',
    closeColorHoverNeutral: 'var(--gds-color-bg-neutral)',
    closeColorPressedNeutral: 'var(--gds-color-bg-neutral-dark2)',
    borderNeutral: '1px solid var(--gds-color-border-neutral)',
    checkedBorderedInfo: '1px solid var(--gds-color-border-primary)',
    checkedBorderedError: '1px solid var(--gds-color-border-primary)',
    checkedBorderedSuccess: '1px solid var(--gds-color-border-primary)',
    checkedBorderedNeutral: '1px solid var(--gds-color-border-primary)',
    checkedBorderedPrimary: '1px solid var(--gds-color-border-primary)',
    checkedBorderedWarning: '1px solid var(--gds-color-border-primary)',
    // Primary
    borderPrimary: '1px solid var(--gds-color-border-primary)',
    textColorPrimary: 'var(--gds-color-text-primary)',
    textColorPrimaryChecked: 'var(--gds-color-text-primary)',
    textColorPrimaryUnchecked: 'var(--gds-color-text-primary)',
    closeIconColorPrimary: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverPrimary: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedPrimary: 'var(--gds-color-icon-neutral)',
    colorPrimary: 'var(--gds-color-bg-primary-light2)',
    iconColorPrimary: 'var(--gds-color-icon-primary)',
    iconColorPrimaryChecked: 'var(--gds-color-icon-primary)',
    colorBorderedPrimary: 'var(--gds-color-bg-primary-light2)',
    colorHoverPrimary: 'var(--gds-color-bg-primary-light2)',
    colorPressedPrimary: 'var(--gds-color-bg-primary-dark2)',
    colorCheckedPrimary: 'var(--gds-color-bg-primary-light2)',
    closeColorHoverPrimary: 'var(--gds-color-bg-primary-light2)',
    closeColorPressedPrimary: 'var(--gds-color-bg-primary-light2)',
    // Info
    textColorInfo: 'var(--gds-color-text-info)',
    textColorInfoChecked: 'var(--gds-color-text-info)',
    textColorInfoUnchecked: 'var(--gds-color-text-info)',
    closeIconColorInfo: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverInfo: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedInfo: 'var(--gds-color-icon-neutral)',
    borderInfo: '1px solid var(--gds-color-border-info-dark2)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorInfoChecked: 'var(--gds-color-icon-info)',
    colorInfo: 'var(--gds-color-bg-info-light2)',
    colorBorderedInfo: 'var(--gds-color-bg-info-light2)',
    colorHoverInfo: 'var(--gds-color-bg-info-light2)',
    colorPressedInfo: 'var(--gds-color-bg-info-light2)',
    colorCheckedInfo: 'var(--gds-color-bg-info-light2)',
    closeColorHoverInfo: 'var(--gds-color-bg-info)',
    closeColorPressedInfo: 'var(--gds-color-bg-info)',
    // Success
    borderSuccess: '1px solid var(--gds-color-border-success)',
    textColorSuccess: 'var(--gds-color-text-success)',
    textColorSuccessChecked: 'var(--gds-color-text-success)',
    textColorSuccessUnchecked: 'var(--gds-color-text-success)',
    closeIconColorSuccess: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverSuccess: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedSuccess: 'var(--gds-color-icon-neutral)',
    colorSuccess: 'var(--gds-color-bg-success)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorSuccessChecked: 'var(--gds-color-icon-success)',
    colorBorderedSuccess: 'var(--gds-color-bg-success-light2)',
    colorHoverSuccess: 'var(--gds-color-bg-success-light2)',
    colorPressedSuccess: 'var(--gds-color-bg-success-light2)',
    colorCheckedSuccess: 'var(--gds-color-bg-success)',
    closeColorHoverSuccess: 'var(--gds-color-bg-success-light1)',
    closeColorPressedSuccess: 'var(--gds-color-bg-success-light1)',
    // Warning
    borderWarning: '1px solid var(--gds-color-border-warning-dark)',
    textColorWarning: 'var(--gds-color-text-warning)',
    textColorWarningChecked: 'var(--gds-color-text-warning)',
    textColorWarningUnchecked: 'var(--gds-color-text-warning)',
    closeIconColorWarning: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverWarning: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedWarning: 'var(--gds-color-icon-neutral)',
    colorWarning: 'var(--gds-color-bg-warning)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    iconColorWarningChecked: 'var(--gds-color-icon-warning)',
    colorBorderedWarning: 'var(--gds-color-bg-warning-light2)',
    colorHoverWarning: 'var(--gds-color-bg-warning-light2)',
    colorPressedWarning: 'var(--gds-color-bg-warning-light2)',
    colorCheckedWarning: 'var(--gds-color-bg-warning)',
    closeColorHoverWarning: 'var(--gds-color-bg-warning-light1)',
    closeColorPressedWarning: 'var(--gds-color-bg-warning-light1)',
    //
    badgeBorderColorPrimary: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorPrimaryChecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorPrimaryUnchecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorInfo: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorInfoChecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorInfoUnchecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorNeutral: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorNeutralChecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorNeutralUnchecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorSuccess: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorSuccessChecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorSuccessUnchecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorWarning: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorWarningChecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorWarningUnchecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorError: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorErrorChecked: 'var(--gds-color-bg-neutral-light)',
    badgeBorderColorErrorUnchecked: 'var(--gds-color-bg-neutral-light)',
    // Error
    borderError: '1px solid var(--gds-color-border-danger-dark)',
    textColorError: 'var(--gds-color-text-danger)',
    textColorErrorChecked: 'var(--gds-color-text-danger)',
    textColorErrorUnchecked: 'var(--gds-color-text-danger)',
    closeIconColorError: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverError: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedError: 'var(--gds-color-icon-neutral)',
    colorError: 'var(--gds-color-bg-danger)',
    iconColorError: 'var(--gds-color-icon-danger)',
    iconColorErrorChecked: 'var(--gds-color-icon-danger)',
    colorBorderedError: 'var(--gds-color-bg-danger-light2)',
    colorHoverError: 'var(--gds-color-bg-danger-light3)',
    colorPressedError: 'var(--gds-color-bg-danger-light3)',
    colorCheckedError: 'var(--gds-color-bg-danger)',
    closeColorHoverError: 'var(--gds-color-bg-danger-light2)',
    closeColorPressedError: 'var(--gds-color-bg-danger-light2)'
  },
  Filter: {
    fontSize: 'var(--gds-font-size-14)',
    textColor: 'var(--gds-color-text-neutral-light2)',
    valueTextColor: 'var(--gds-color-text-primary)',
    tagBackgroundColor: 'var(--gds-color-bg-dark)',
    labelTextColor: 'var(--gds-color-text-neutral-light2)',
    actionBorderColor: 'var(--gds-color-border-neutral-dark2)',
    resetTextColor: 'var(--gds-color-text-neutral-light2)',
    tagHoverColor: 'var(--gds-color-bg-neutral)',
    tagActiveColor: 'var(--gds-color-bg-neutral)',
    resetColor: 'var(--gds-color-icon-neutral)'
  },
  Form: {
    blankHeightSmall: '28px',
    blankHeightMedium: '34px',
    blankHeightLarge: '40px',
    lineHeight: '1.6',
    inputBackgroundColor: 'var(--gds-color-bg-neutral)',
    labelTextColor: 'var(--gds-color-text-neutral)',
    labelDescriptionTextColor: 'var(--gds-color-text-neutral-light2)',
    helpIconColor: 'var(--gds-color-icon-neutral)',
    asteriskColor: 'var(--gds-color-icon-danger)',
    feedbackTextColorSuccess: 'var(--gds-color-text-success)',
    feedbackTextColorNeutral: 'var(--gds-color-text-neutral)',
    feedbackTextColorError: 'var(--gds-color-text-danger)',
    feedbackTextColorWarning: 'var(--gds-color-text-warning)',
    feedbackIconColorNeutral: 'var(--gds-color-icon-neutral)',
    feedbackIconColorWarning: 'var(--gds-color-icon-warning)',
    feedbackIconColorError: 'var(--gds-color-icon-danger)',
    feedbackIconColorSuccess: 'var(--gds-color-icon-success)',
    feedbackTextColor: 'var(--gds-color-text-neutral)'
  },
  FloatingPanel: {
    borderRadius: 'var(--gds-border-radius-m)',
    lineHeight: '1.6',
    fontSize: 'var(--gds-font-size-14)',
    headerFontWeight: 500,
    descriptionFontSize: ' var(--gds-font-size-14)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    toggleBorderRadius: 'var(--gds-border-radius-xs)',
    newTabBorderRadius: 'var(--gds-border-radius-xs)',
    iconColor: 'var(--gds-color-icon-neutral)',
    color: 'var(--gds-color-bg-dark)',
    panelDividerColor: 'var(--gds-color-border-neutral)',
    textColor: 'var(--gds-color-text-neutral)',
    closeIconColor: 'var(--gds-color-icon-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    closeColorHover: 'var(--gds-color-bg-neutral-dark1)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark2)',
    toggleColorHover: 'var(--gds-color-bg-neutral-dark1)',
    toggleColorPressed: 'var(--gds-color-bg-neutral-dark2)',
    toggleIconColor: 'var(--gds-color-icon-neutral)',
    toggleIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    toggleIconColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    newTabColorHover: 'var(--gds-color-bg-neutral-dark1)',
    newTabColorPressed: 'var(--gds-color-bg-neutral-dark2)',
    newTabIconColor: 'var(--gds-color-icon-neutral)',
    newTabIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    newTabIconColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    toolbarBackgroundColor: 'var(--gds-color-bg-primary)',
    toolbarBackgroundColorHover: 'var(--gds-color-bg-primary-dark1)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    actionTextColor: 'var(--gds-color-text-neutral)'
  },
  DetailsView: {
    detailsViewLabelColor: 'var(--gds-color-text-neutral-light2)',
    detailsViewValueColor: 'var(--gds-color-text-neutral-light1)',
    color: 'var(--gds-color-bg-dark)',
    dividerColor: 'var(--gds-color-border-neutral)',
    expandedBackgroundColor: 'var(--gds-color-bg-light)'
  },
  Divider: {
    textColor: 'var(--gds-color-text-neutral)',
    color: 'var(--gds-color-border-neutral)'
  },
  Image: {
    toolbarIconColor: 'var(--gds-color-icon-inverse)',
    toolbarColor: 'var(--gds-color-bg-primary-dark2)',
    opacity: 0.4
  },
  List: {
    textColor: 'var(--gds-color-text-neutral-light2)',
    color: 'var(--gds-color-bg-dark)',
    colorHover: 'var(--gds-color-bg-dark)',
    colorModal: 'var(--gds-color-bg-dark)',
    colorPopover: 'var(--gds-color-bg-dark)',
    borderColor: 'var(--gds-color-border-neutral)',
    borderRadius: 'var(--gds-border-radius-xs)',
    fontSize: 'var(--gds-font-size-14)',
    colorHoverPopover: 'var(--gds-color-bg-dark2)',
    colorHoverModal: 'var(--gds-color-bg-dark2)',
    borderColorModal: 'var(--gds-color-border-neutral)',
    borderColorPopover: 'var(--gds-color-border-neutral)'
  },
  Modal: {
    color: 'var(--gds-color-bg-dark)',
    textColor: 'var(--gds-color-text-neutral)'
  },
  Popover: {
    fontSize: 'var(--gds-font-size-14)',
    borderRadius: 'var(--gds-border-radius-xs)',
    dividerColor: 'var(--gds-color-border-neutral)',
    bgColor: 'var(--gds-color-bg-neutral)',
    textColor: 'var(--gds-color-text-light)'
  },
  Timeline: {
    contentFontSize: 'var(--gds-font-size-14)',
    titleFontWeight: 500,
    circleBorder: '2px solid var(--gds-color-border-neutral-dark2)',
    circleBorderNeutral: '2px solid var(--gds-color-border-neutral-dark2)',
    circleBorderInfo: '2px solid var(--gds-color-border-info-dark1)',
    circleBorderError: '2px solid var(--gds-color-border-danger-dark)',
    circleBorderSuccess: '2px solid var(--gds-color-border-success-dark)',
    circleBorderWarning: '2px solid var(--gds-color-border-warning-dark)',
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorNeutral: 'var(--gds-color-icon-neutral)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorError: 'var(--gds-color-icon-danger)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    contentTextColor: 'var(--gds-color-text-neutral-light1)',
    metaTextColor: 'var(--gds-color-text-neutral-light2)',
    lineColor: 'var(--gds-color-border-neutral)'
  },
  Card: {
    boxShadow:
      '0px 8px 16px -4px rgba(2, 13, 75, 0.25), 0px 0px 1px 0px rgba(2, 13, 75, 0.30)',

    // border implementation using shadow
    borderShadow:
      '0px 1px 1px 0px rgba(2, 13, 75, 0.25), 0px 0px 1px 0px rgba(2, 13, 75, 0.30)',
    selectionShadow: '0 0 0 2px #263eb3',
    // remove old border implementation
    borderWidth: '0',
    color: 'var(--gds-color-bg-dark)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    colorModal: 'var(--gds-color-bg-dark)',
    colorPopover: 'var(--gds-color-bg-dark)',
    colorTarget: 'var(--gds-color-bg-primary)',
    colorEmbedded: 'var(--gds-color-bg-dark)',
    colorEmbeddedCheckbox: 'var(--gds-color-bg-primary)',
    colorEmbeddedModal: 'var(--gds-color-bg-dark)',
    colorEmbeddedPopover: 'var(--gds-color-bg-dark)',
    colorActionArea: 'var(--gds-color-bg-dark)',
    borderColor: 'var(--gds-color-border-neutral-dark1)',
    actionAreaColor: 'var(--gds-color-bg-dark)',
    closeColorHover: 'var(--gds-color-bg-button-tertiary-dark1)',
    closeColorPressed: 'var(--gds-color-bg-button-tertiary-dark2)',
    closeIconColor: 'var(--gds-color-icon-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)'
  }
}
