export default {
  backSize: '16px',
  titleFontSizeXSmall: '14px',
  titleFontSizeSmall: '14px',
  titleFontSizeMedium: '16px',
  titleFontSizeLarge: '20px',
  titleFontSizeXLarge: '24px',
  descriptionFontSizeXSmall: '12px',
  descriptionFontSizeSmall: '12px',
  descriptionFontSizeMedium: '14px',
  descriptionFontSizeLarge: '16px',
  descriptionFontSizeXLarge: '16px',
  paddingSizeXSmall: '4px 6px',
  paddingSizeSmall: '8px 12px',
  paddingSizeMedium: '16px 24px',
  paddingSizeLarge: '24px 36px',
  paddingSizeXLarge: '48px 64px',
  radiusNone: '0px',
  radiusXSmall: '2px',
  radiusSmall: '4px',
  radiusMedium: '8px',
  radiusLarge: '16px',
  radiusXLarge: '24px'
}
