<markdown>
# Autogenerated file list

The file list can be generated automatically by setting the `auto-file-list` prop to `true`.

</markdown>

<template>
  <z-upload
    v-model:file-list="fileList"
    action="https://robohash.org/0e01f2b7f17b44c5db9f7602631e7240"
    @update:file-list="handleFileListChange"
    @change="handleUploadChange"
    @remove="handleRemove"
  >
    <z-button>Upload File</z-button>
  </z-upload>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import { useMessage } from '@zeta-gds/components'
import type { UploadFileInfo } from '@zeta-gds/components'

export default defineComponent({
  setup () {
    const message = useMessage()
    const fileListRef = ref<UploadFileInfo[]>([
      {
        id: 'url-test',
        name: 'URL Test.pdf',
        status: 'finished'
      },
      {
        id: 'text-message',
        name: 'Your text messages.pdf',
        status: 'error'
      },
      {
        id: 'notification',
        name: 'You notifications.pdf',
        status: 'finished'
      },
      {
        id: 'contact',
        name: 'You contact info.pdf',
        status: 'finished'
      }
    ])
    return {
      fileList: fileListRef,
      handleUploadChange (data: { fileList: UploadFileInfo[] }) {
        fileListRef.value = data.fileList
      },
      handleRemove (data: { file: UploadFileInfo; fileList: UploadFileInfo[] }) {
        if (data.file.id === 'text-message') {
          message.info("Oops... It's now uploaded. Okay, delete it.")
        } else if (data.file.id === 'notification') {
          message.error('No, this is useful for us. Removal not allowed.')
          return false
        } else if (data.file.id === 'contact') {
          message.loading(
            "Don' know whether it is useful for us, let me ask the server",
            {
              duration: 4000
            }
          )
          return new Promise((resolve) => {
            setTimeout(() => {
              message.error("Oh no, they said you can't delete it too!")
              resolve(false)
            }, 4000)
          })
        }
      },
      handleFileListChange () {
        message.info('Yes, file-list changed.')
      }
    }
  }
})
</script>
