import commonVariables from './_common'
import { changeColor, scaleColor } from 'seemly'
import { commonDark } from '../../_styles/common'
import type { TagTheme } from './light'

const tagDark: TagTheme = {
  name: 'Tag',
  common: commonDark,
  self (vars) {
    const {
      textColor2,
      primaryColor,
      infoColor,
      successColor,
      warningColor,
      errorColor,
      borderColor,
      tagColor,
      opacityDisabled,
      closeIconColor,
      closeIconColorHover,
      closeIconColorPressed,
      closeColorHover,
      closeColorPressed,
      borderRadiusSmall: borderRadius,
      fontSizeMini,
      fontSizeXSmall,
      fontSizeSmall,
      fontSizeMedium,
      heightMini,
      heightXSmall,
      heightSmall,
      heightMedium,
      fontWeightStrong
    } = vars
    return {
      ...commonVariables,
      closeBorderRadius: borderRadius,
      heightXSmall: heightMini,
      heightSmall: heightXSmall,
      heightMedium: heightSmall,
      heightLarge: heightMedium,
      borderRadius,
      opacityDisabled,
      fontSizeXSmall: fontSizeMini,
      fontSizeSmall: fontSizeXSmall,
      fontSizeMedium: fontSizeSmall,
      fontSizeLarge: fontSizeMedium,
      fontWeightStrong,
      // checked
      borderChecked: '1px solid #2A4FF0',
      // focus
      borderFocused: '#2A4FF0',

      // default
      borderNeutral: `1px solid ${borderColor}`,
      textColorNeutral: textColor2,
      textColorNeutralChecked: textColor2,
      textColorNeutralUnchecked: textColor2,
      colorNeutral: tagColor,
      iconColorNeutral: textColor2,
      iconColorNeutralChecked: textColor2,
      colorBorderedNeutral: '#0000',
      colorHoverNeutral: tagColor,
      colorPressedNeutral: tagColor,
      colorCheckedNeutral: tagColor,
      checkedBorderedInfo: '1px solid #2A4FF0',
      checkedBorderedError: '1px solid #2A4FF0',
      checkedBorderedSuccess: '1px solid #2A4FF0',
      checkedBorderedNeutral: '1px solid #2A4FF0',
      checkedBorderedPrimary: '1px solid #2A4FF0',
      checkedBorderedWarning: '1px solid #2A4FF0',
      closeIconColorNeutral: closeIconColor,
      closeIconColorHoverNeutral: closeIconColorHover,
      closeIconColorPressedNeutral: closeIconColorPressed,
      closeColorHoverNeutral: closeColorHover,
      closeColorPressedNeutral: closeColorPressed,

      // primary
      borderPrimary: `1px solid ${changeColor(primaryColor, { alpha: 0.3 })}`,
      textColorPrimary: primaryColor,
      textColorPrimaryChecked: primaryColor,
      textColorPrimaryUnchecked: primaryColor,
      colorPrimary: changeColor(primaryColor, { alpha: 0.16 }),
      iconColorPrimary: changeColor(primaryColor, { alpha: 0.16 }),
      iconColorPrimaryChecked: changeColor(primaryColor, { alpha: 0.16 }),
      iconColorPrimaryUnchecked: changeColor(primaryColor, { alpha: 0.16 }),
      colorBorderedPrimary: '#0000',
      colorHoverPrimary: changeColor(primaryColor, { alpha: 0.16 }),
      colorPressedPrimary: changeColor(primaryColor, { alpha: 0.12 }),
      colorCheckedPrimary: changeColor(primaryColor, { alpha: 0.12 }),
      closeIconColorPrimary: scaleColor(primaryColor, { lightness: 0.7 }),
      closeIconColorHoverPrimary: scaleColor(primaryColor, { lightness: 0.7 }),
      closeIconColorPressedPrimary: scaleColor(primaryColor, {
        lightness: 0.7
      }),
      closeColorHoverPrimary: changeColor(primaryColor, { alpha: 0.16 }),
      closeColorPressedPrimary: changeColor(primaryColor, { alpha: 0.12 }),

      // Info
      borderInfo: `1px solid ${changeColor(infoColor, { alpha: 0.3 })}`,
      colorHoverInfo: changeColor(infoColor, { alpha: 0.16 }),
      colorPressedInfo: changeColor(infoColor, { alpha: 0.12 }),
      colorCheckedInfo: changeColor(infoColor, { alpha: 0.12 }),
      textColorInfo: infoColor,
      textColorInfoChecked: infoColor,
      textColorInfoUnchecked: infoColor,
      colorInfo: changeColor(infoColor, { alpha: 0.16 }),
      iconColorInfo: changeColor(infoColor, { alpha: 0.16 }),
      iconColorInfoChecked: changeColor(infoColor, { alpha: 0.16 }),
      colorBorderedInfo: '#0000',
      closeIconColorInfo: scaleColor(infoColor, { alpha: 0.7 }),
      closeIconColorHoverInfo: scaleColor(infoColor, { alpha: 0.7 }),
      closeIconColorPressedInfo: scaleColor(infoColor, { alpha: 0.7 }),
      closeColorHoverInfo: changeColor(infoColor, { alpha: 0.16 }),
      closeColorPressedInfo: changeColor(infoColor, { alpha: 0.12 }),

      // Success
      borderSuccess: `1px solid ${changeColor(successColor, { alpha: 0.3 })}`,
      textColorSuccess: successColor,
      textColorSuccessChecked: successColor,
      textColorSuccessUnchecked: successColor,
      colorSuccess: changeColor(successColor, { alpha: 0.16 }),
      iconColorSuccess: changeColor(successColor, { alpha: 0.16 }),
      iconColorSuccessChecked: changeColor(successColor, { alpha: 0.16 }),
      colorBorderedSuccess: '#0000',
      colorHoverSuccess: changeColor(successColor, { alpha: 0.16 }),
      colorPressedSuccess: changeColor(successColor, { alpha: 0.2 }),
      colorCheckedSuccess: changeColor(successColor, { alpha: 0.2 }),
      closeIconColorSuccess: scaleColor(successColor, { alpha: 0.7 }),
      closeIconColorHoverSuccess: scaleColor(successColor, { alpha: 0.7 }),
      closeIconColorPressedSuccess: scaleColor(successColor, { alpha: 0.7 }),
      closeColorHoverSuccess: changeColor(successColor, { alpha: 0.16 }),
      closeColorPressedSuccess: changeColor(successColor, { alpha: 0.12 }),

      // Warning
      borderWarning: `1px solid ${changeColor(warningColor, { alpha: 0.3 })}`,
      textColorWarning: warningColor,
      textColorWarningChecked: warningColor,
      textColorWarningUnchecked: warningColor,
      colorWarning: changeColor(warningColor, { alpha: 0.16 }),
      iconColorWarning: changeColor(warningColor, { alpha: 0.16 }),
      iconColorWarningChecked: changeColor(warningColor, { alpha: 0.16 }),
      colorBorderedWarning: '#0000',
      colorHoverWarning: changeColor(warningColor, { alpha: 0.16 }),
      colorPressedWarning: changeColor(warningColor, { alpha: 0.2 }),
      colorCheckedWarning: changeColor(warningColor, { alpha: 0.2 }),
      closeIconColorWarning: scaleColor(warningColor, { alpha: 0.7 }),
      closeIconColorHoverWarning: scaleColor(warningColor, { alpha: 0.7 }),
      closeIconColorPressedWarning: scaleColor(warningColor, { alpha: 0.7 }),
      closeColorHoverWarning: changeColor(warningColor, { alpha: 0.16 }),
      closeColorPressedWarning: changeColor(warningColor, { alpha: 0.11 }),

      // Error
      borderError: `1px solid ${changeColor(errorColor, { alpha: 0.3 })}`,
      textColorError: errorColor,
      textColorErrorChecked: errorColor,
      textColorErrorUnchecked: errorColor,
      colorError: changeColor(errorColor, { alpha: 0.16 }),
      iconColorError: changeColor(errorColor, { alpha: 0.16 }),
      iconColorErrorChecked: changeColor(errorColor, { alpha: 0.16 }),
      colorBorderedError: '#0000',
      colorHoverError: changeColor(errorColor, { alpha: 0.16 }),
      colorPressedError: changeColor(errorColor, { alpha: 0.12 }),
      colorCheckedError: changeColor(errorColor, { alpha: 0.12 }),
      closeIconColorError: scaleColor(errorColor, { alpha: 0.7 }),
      closeIconColorHoverError: scaleColor(errorColor, { alpha: 0.7 }),
      closeIconColorPressedError: scaleColor(errorColor, { alpha: 0.7 }),
      closeColorHoverError: changeColor(errorColor, { alpha: 0.16 }),
      closeColorPressedError: changeColor(errorColor, { alpha: 0.12 }),

      //
      badgeBorderColorPrimary: '#D4D7E6',
      badgeBorderColorPrimaryChecked: '#D4D7E6',
      badgeBorderColorPrimaryUnchecked: '#D4D7E6',
      badgeBorderColorInfo: '#D4D7E6',
      badgeBorderColorInfoChecked: '#D4D7E6',
      badgeBorderColorInfoUnchecked: '#D4D7E6',
      badgeBorderColorNeutral: '#D4D7E6',
      badgeBorderColorNeutralChecked: '#D4D7E6',
      badgeBorderColorNeutralUnchecked: '#D4D7E6',
      badgeBorderColorSuccess: '#D4D7E6',
      badgeBorderColorSuccessChecked: '#D4D7E6',
      badgeBorderColorSuccessUnchecked: '#D4D7E6',
      badgeBorderColorWarning: '#D4D7E6',
      badgeBorderColorWarningChecked: '#D4D7E6',
      badgeBorderColorWarningUnchecked: '#D4D7E6',
      badgeBorderColorError: '#D4D7E6',
      badgeBorderColorErrorChecked: '#D4D7E6',
      badgeBorderColorErrorUnchecked: '#D4D7E6'
    }
  }
}

export default tagDark
