import commonVariables from './_common'
import { changeColor } from 'seemly'
import { commonLight } from '../../_styles/common'
import type { ThemeCommonVars } from '../../_styles/common'
import type { Theme } from '../../_mixins'

const self = (vars: ThemeCommonVars) => {
  const {
    primaryColor,
    infoColor,
    successColor,
    warningColor,
    errorColor,
    opacityDisabled,
    borderRadius,
    fontSizeMini,
    fontSizeXSmall,
    fontSizeSmall,
    fontSizeMedium,
    heightMini,
    heightXSmall,
    heightSmall,
    heightMedium,
    fontWeightStrong
  } = vars
  return {
    ...commonVariables,
    closeBorderRadius: borderRadius,
    heightXSmall: heightMini,
    heightSmall: heightXSmall,
    heightMedium: heightSmall,
    heightLarge: heightMedium,
    borderRadius,
    opacityDisabled,
    fontSizeXSmall: fontSizeMini,
    fontSizeSmall: fontSizeXSmall,
    fontSizeMedium: fontSizeSmall,
    fontSizeLarge: fontSizeMedium,
    fontWeightStrong,
    // checked
    borderChecked: '1px solid #2A4FF0',
    // focus
    borderFocused: '#2A4FF0',
    // default
    borderNeutral: '1px solid var(--gds-color-border-neutral-dark1)',
    textColorNeutral: '#434B79',
    textColorNeutralChecked: '#434B79',
    textColorNeutralUnchecked: '#434B79',
    colorNeutral: '#F1F2F8',
    iconColorNeutral: '#7D83A6',
    iconColorNeutralChecked: '#7D83A6',
    colorBorderedNeutral: 'var(--gds-color-bg-neutral-light)',
    colorHoverNeutral: '#E6E7F2',
    colorPressedNeutral: '#D4D7E6',
    colorCheckedNeutral: '#F1F2F8',
    closeIconColorNeutral: '#7D83A6',
    closeIconColorHoverNeutral: '#7D83A6',
    closeIconColorPressedNeutral: '#7D83A6',
    closeColorHoverNeutral: '#1C275F0F',
    closeColorPressedNeutral: '#1C275f1A',
    checkedBorderedInfo: '1px solid #2A4FF0',
    checkedBorderedError: '1px solid #2A4FF0',
    checkedBorderedSuccess: '1px solid #2A4FF0',
    checkedBorderedNeutral: '1px solid #2A4FF0',
    checkedBorderedPrimary: '1px solid #2A4FF0',
    checkedBorderedWarning: '1px solid #2A4FF0',
    // Primary
    borderPrimary: `1px solid ${changeColor(primaryColor, { alpha: 0.3 })}`,
    textColorPrimary: primaryColor,
    textColorPrimaryChecked: primaryColor,
    textColorPrimaryUnchecked: primaryColor,
    colorPrimary: changeColor(primaryColor, { alpha: 0.12 }),
    iconColorPrimary: changeColor(primaryColor, { alpha: 0.12 }),
    iconColorPrimaryChecked: changeColor(primaryColor, { alpha: 0.12 }),
    colorBorderedPrimary: changeColor(primaryColor, { alpha: 0.1 }),
    colorHoverPrimary: changeColor(primaryColor, { alpha: 0.12 }),
    colorPressedPrimary: changeColor(primaryColor, { alpha: 0.18 }),
    colorCheckedPrimary: changeColor(primaryColor, { alpha: 0.18 }),
    closeIconColorPrimary: primaryColor,
    closeIconColorHoverPrimary: primaryColor,
    closeIconColorPressedPrimary: primaryColor,
    closeColorHoverPrimary: changeColor(primaryColor, { alpha: 0.12 }),
    closeColorPressedPrimary: changeColor(primaryColor, { alpha: 0.18 }),
    // Info
    borderInfo: `1px solid ${changeColor(infoColor, { alpha: 0.3 })}`,
    textColorInfo: infoColor,
    textColorInfoChecked: infoColor,
    textColorInfoUnchecked: infoColor,
    iconColorInfo: changeColor(infoColor, { alpha: 0.12 }),
    iconColorInfoChecked: changeColor(infoColor, { alpha: 0.12 }),
    colorInfo: changeColor(infoColor, { alpha: 0.12 }),
    colorBorderedInfo: changeColor(infoColor, { alpha: 0.1 }),
    colorHoverInfo: changeColor(infoColor, { alpha: 0.12 }),
    colorPressedInfo: changeColor(infoColor, { alpha: 0.18 }),
    colorCheckedInfo: changeColor(infoColor, { alpha: 0.18 }),
    closeIconColorInfo: infoColor,
    closeIconColorHoverInfo: infoColor,
    closeIconColorPressedInfo: infoColor,
    closeColorHoverInfo: changeColor(infoColor, { alpha: 0.12 }),
    closeColorPressedInfo: changeColor(infoColor, { alpha: 0.18 }),
    // Success
    borderSuccess: `1px solid ${changeColor(successColor, { alpha: 0.3 })}`,
    textColorSuccess: successColor,
    textColorSuccessChecked: successColor,
    textColorSuccessUnchecked: successColor,
    colorSuccess: changeColor(successColor, { alpha: 0.12 }),
    iconColorSuccess: changeColor(successColor, { alpha: 0.12 }),
    iconColorSuccessChecked: changeColor(successColor, { alpha: 0.12 }),
    colorBorderedSuccess: changeColor(successColor, { alpha: 0.1 }),
    colorHoverSuccess: changeColor(successColor, { alpha: 0.12 }),
    colorPressedSuccess: changeColor(successColor, { alpha: 0.18 }),
    colorCheckedSuccess: changeColor(successColor, { alpha: 0.18 }),
    closeIconColorSuccess: successColor,
    closeIconColorHoverSuccess: successColor,
    closeIconColorPressedSuccess: successColor,
    closeColorHoverSuccess: changeColor(successColor, { alpha: 0.12 }),
    closeColorPressedSuccess: changeColor(successColor, { alpha: 0.18 }),
    // Warning
    borderWarning: `1px solid ${changeColor(warningColor, { alpha: 0.35 })}`,
    textColorWarning: warningColor,
    textColorWarningChecked: warningColor,
    textColorWarningUnchecked: warningColor,
    colorWarning: changeColor(warningColor, { alpha: 0.15 }),
    iconColorWarning: changeColor(warningColor, { alpha: 0.15 }),
    iconColorWarningChecked: changeColor(warningColor, { alpha: 0.15 }),
    colorBorderedWarning: changeColor(warningColor, { alpha: 0.12 }),
    colorHoverWarning: changeColor(warningColor, { alpha: 0.12 }),
    colorPressedWarning: changeColor(warningColor, { alpha: 0.18 }),
    colorCheckedWarning: changeColor(warningColor, { alpha: 0.18 }),
    closeIconColorWarning: warningColor,
    closeIconColorHoverWarning: warningColor,
    closeIconColorPressedWarning: warningColor,
    closeColorHoverWarning: changeColor(warningColor, { alpha: 0.12 }),
    closeColorPressedWarning: changeColor(warningColor, { alpha: 0.18 }),
    //
    badgeBorderColorPrimary: '#D4D7E6',
    badgeBorderColorPrimaryChecked: '#D4D7E6',
    badgeBorderColorPrimaryUnchecked: '#D4D7E6',
    badgeBorderColorInfo: '#D4D7E6',
    badgeBorderColorInfoChecked: '#D4D7E6',
    badgeBorderColorInfoUnchecked: '#D4D7E6',
    badgeBorderColorNeutral: '#D4D7E6',
    badgeBorderColorNeutralChecked: '#D4D7E6',
    badgeBorderColorNeutralUnchecked: '#D4D7E6',
    badgeBorderColorSuccess: '#D4D7E6',
    badgeBorderColorSuccessChecked: '#D4D7E6',
    badgeBorderColorSuccessUnchecked: '#D4D7E6',
    badgeBorderColorWarning: '#D4D7E6',
    badgeBorderColorWarningChecked: '#D4D7E6',
    badgeBorderColorWarningUnchecked: '#D4D7E6',
    badgeBorderColorError: '#D4D7E6',
    badgeBorderColorErrorChecked: '#D4D7E6',
    badgeBorderColorErrorUnchecked: '#D4D7E6',
    // Error
    borderError: `1px solid ${changeColor(errorColor, { alpha: 0.23 })}`,
    textColorError: errorColor,
    textColorErrorChecked: errorColor,
    textColorErrorUnchecked: errorColor,
    colorError: changeColor(errorColor, { alpha: 0.1 }),
    iconColorError: changeColor(errorColor, { alpha: 0.1 }),
    iconColorErrorChecked: changeColor(errorColor, { alpha: 0.1 }),
    colorBorderedError: changeColor(errorColor, { alpha: 0.08 }),
    colorHoverError: changeColor(errorColor, { alpha: 0.12 }),
    colorPressedError: changeColor(errorColor, { alpha: 0.18 }),
    colorCheckedError: changeColor(errorColor, { alpha: 0.18 }),
    closeIconColorError: errorColor,
    closeIconColorHoverError: errorColor,
    closeIconColorPressedError: errorColor,
    closeColorHoverError: changeColor(errorColor, { alpha: 0.12 }),
    closeColorPressedError: changeColor(errorColor, { alpha: 0.18 })
  }
}

export type TagThemeVars = ReturnType<typeof self>

const tagLight: Theme<'Tag', TagThemeVars> = {
  name: 'Tag',
  common: commonLight,
  self
}

export default tagLight
export type TagTheme = typeof tagLight
