export default {
  padding: '8px 0px',
  optionIconSizeXSmall: '12px',
  optionIconSizeSmall: '14px',
  optionIconSizeMedium: '16px',
  optionIconSizeLarge: '16px',
  optionIconSizeXLarge: '18px',
  optionSuffixWidthXSmall: '16px',
  optionSuffixWidthSmall: '16px',
  optionSuffixWidthMedium: '16px',
  optionSuffixWidthLarge: '16px',
  optionSuffixWidthXLarge: '16px',
  optionIconSuffixWidthXSmall: '28px',
  optionIconSuffixWidthSmall: '32px',
  optionIconSuffixWidthMedium: '32px',
  optionIconSuffixWidthLarge: '36px',
  optionIconSuffixWidthXLarge: '36px',
  optionPrefixWidthXSmall: '16px',
  optionPrefixWidthSmall: '16px',
  optionPrefixWidthMedium: '16px',
  optionPrefixWidthLarge: '16px',
  optionPrefixWidthXLarge: '16px',
  optionIconPrefixWidthXSmall: '32px',
  optionIconPrefixWidthSmall: '36px',
  optionIconPrefixWidthMedium: '36px',
  optionIconPrefixWidthLarge: '40px',
  optionIconPrefixWidthXLarge: '40px'
}
