import { changeColor } from 'seemly'
import type { GlobalThemeOverrides } from '@zeta-gds/components'

export const themeOverridesLight: GlobalThemeOverrides = {
  common: {
    fontFamily:
      '"IBM Plex Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    fontFamilyMono:
      '"IBM Plex Mono", SFMono-Regular, Menlo, Consolas, Courier, monospace'
  },
  Switch: {
    opacityDisabled: '0.4',
    iconColor: 'var(--gds-color-icon-neutral)',
    textColor: 'var(--gds-color-text-light)',
    loadingColor: 'var(--gds-color-border-primary)',
    railColor: 'var(--gds-color-bg-neutral-dark1)',
    railColorHover: 'var(--gds-color-bg-neutral-dark3)',
    railColorActive: 'var(--gds-color-bg-primary)',
    railColorActiveHover: 'var(--gds-color-bg-primary-dark1)',
    buttonColor: 'var(--gds-color-bg-neutral)',
    railBorderRadiusSmall: 'var(--gds-border-radius-xs)',
    railBorderRadiusMedium: 'var(--gds-border-radius-xs)',
    railBorderRadiusLarge: 'var(--gds-border-radius-xs)',
    buttonBorderRadiusSmall: 'var(--gds-border-radius-xs)',
    buttonBorderRadiusMedium: 'var(--gds-border-radius-xs)',
    buttonBorderRadiusLarge: 'var(--gds-border-radius-xs)',
    boxShadowFocus: '0 0 0 2px var(--gds-color-border-primary-light)',
    buttonBoxShadow: `0px 4px 8px -2px hsla(231, 95%, 15%, 0.25),
    0px 0px 1px 0px hsla(231, 95%, 15%, 0.3)`
  },
  Menu: {
    borderRadius: 'var(--gds-border-radius-xs)',
    itemColorActive: 'var(--gds-color-bg-primary-light1)',
    itemColorActiveHover: 'var(--gds-color-bg-neutral)',
    itemColorActiveCollapsed: 'var(--gds-color-bg-neutral)',
    color: 'var(--gds-color-bg-light)',
    groupTextColor: 'var(--gds-color-text-inverse)',
    itemColorHover: 'var(--gds-color-bg-neutral)',
    itemTextColor: 'var(--gds-color-text-neutral)',
    itemTextColorHover: 'var(--gds-color-text-neutral)',
    itemTextColorActive: 'var(--gds-color-text-primary)',
    itemTextColorActiveHover: 'var(--gds-color-text-primary)',
    itemTextColorChildActive: 'var(--gds-color-text-primary)',
    itemTextColorChildActiveHover: 'var(--gds-color-text-primary)',
    itemIconColor: 'var(--gds-color-icon-inverse-dark)',
    itemIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    itemIconColorActive: 'var(--gds-color-icon-primary)',
    itemIconColorActiveHover: 'var(--gds-color-icon-primary)',
    itemIconColorChildActive: 'var(--gds-color-icon-primary)',
    itemIconColorChildActiveHover: 'var(--gds-color-icon-primary)',
    itemIconColorCollapsed: 'var(--gds-color-icon-neutral)',
    colorInverted: 'var(--gds-color-bg-nav-dark)',
    itemHeight: '40px',
    fontSize: 'var(--gds-font-size-14)',
    dividerColor: 'var(--gds-color-border-neutral)',

    itemHorizontalHeight: '32px',
    borderColorHorizontal: 'var(--gds-color-border-neutral)',
    // for inverted
    arrowColorInverted: 'var(--gds-color-icon-inverse-dark)',
    arrowColorHoverInverted: 'var(--gds-color-icon-inverse-dark)',
    arrowColorActiveInverted: 'var(--gds-color-icon-inverse-dark)',
    arrowColorActiveHoverInverted: 'var(--gds-color-icon-inverse-dark)',
    arrowColorChildActiveHoverInverted: 'var(--gds-color-icon-neutral-light)',
    arrowColorChildActiveInverted: 'var(--gds-color-icon-neutral-light)',
    itemTextColorHorizontalInverted: 'var(--gds-color-text-inverse)',
    itemTextColorHoverHorizontalInverted: 'var(--gds-color-text-inverse)',
    itemTextColorChildActiveHorizontalInverted: 'var(--gds-color-text-light)',
    itemTextColorChildActiveHoverHorizontalInverted:
      'var(--gds-color-text-light)',
    itemTextColorActiveHorizontalInverted: 'var(--gds-color-text-light)',
    itemTextColorActiveHoverHorizontalInverted: 'var(--gds-color-text-light)',
    itemIconColorHorizontalInverted: 'var(--gds-color-icon-neutral-light)',
    itemIconColorHoverHorizontalInverted: 'var(--gds-color-icon-neutral-light)',
    itemIconColorActiveHorizontalInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorActiveHoverHorizontalInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorChildActiveHorizontalInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorChildActiveHoverHorizontalInverted:
      'var(--gds-color-icon-inverse)',
    itemHoverHorizontalInverted: 'var(--gds-color-bg-nav-dark-light2)',
    itemSelectedHorizontalInverted: 'var(--gds-color-bg-neutral-light)',
    itemHoverActiveHorizontalInverted: 'var(--gds-color-bg-neutral-dark2)',
    // for non-inverted
    arrowColor: 'var(--gds-color-icon-neutral)',
    arrowColorHover: 'var(--gds-color-icon-neutral)',
    arrowColorActive: 'var(--gds-color-icon-neutral)',
    arrowColorActiveHover: 'var(--gds-color-icon-neutral)',
    arrowColorChildActiveHover: 'var(--gds-color-icon-neutral)',
    arrowColorChildActive: 'var(--gds-color-icon-neutral)',
    itemTextColorHorizontal: 'var(--gds-color-text-neutral)',
    itemTextColorHoverHorizontal: 'var(--gds-color-text-light)',
    itemTextColorActiveHorizontal: 'var(--gds-color-text-primary)',
    itemTextColorActiveHoverHorizontal: 'var(--gds-color-text-primary)',
    itemTextColorChildActiveHorizontal: 'var(--gds-color-text-primary)',
    itemTextColorChildActiveHoverHorizontal: 'var(--gds-color-text-primary)',
    itemIconColorHorizontal: 'var(--gds-color-icon-neutral)',
    itemIconColorHoverHorizontal: 'var(--gds-color-icon-neutral)',
    itemIconColorActiveHorizontal: 'var(--gds-color-icon-neutral)',
    itemIconColorActiveHoverHorizontal: 'var(--gds-color-icon-primary)',
    itemIconColorChildActiveHorizontal: 'var(--gds-color-icon-primary)',
    itemIconColorChildActiveHoverHorizontal: 'var(--gds-color-icon-primary)',
    itemHoverHorizontal: 'var(--gds-color-bg-neutral)',
    itemSelectedHorizontal: 'var(--gds-color-bg-neutral-light)',
    itemHoverActiveHorizontal: 'var(--gds-color-bg-neutral-dark1)',

    itemColorHoverInverted: 'var(--gds-color-bg-nav-dark-light1)',
    itemColorActiveInverted: 'var(--gds-color-bg-nav-dark-light2)',
    itemColorActiveHoverInverted: 'var(--gds-color-bg-nav-dark-light1)',
    itemColorActiveCollapsedInverted: 'var(--gds-color-bg-nav-dark-light1)',
    itemTextColorInverted: 'var(--gds-color-text-inverse)',
    itemTextColorHoverInverted: 'var(--gds-color-text-inverse)',
    itemTextColorChildActiveInverted: 'var(--gds-color-text-light)',
    itemTextColorChildActiveHoverInverted: 'var(--gds-color-text-light)',
    itemTextColorActiveInverted: 'var(--gds-color-text-light)',
    itemTextColorActiveHoverInverted: 'var(--gds-color-text-light)',
    itemIconColorInverted: 'var(--gds-color-icon-inverse-dark)',
    itemIconColorHoverInverted: 'var(--gds-color-icon-inverse-dark)',
    itemIconColorActiveInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorActiveHoverInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorChildActiveInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorChildActiveHoverInverted: 'var(--gds-color-icon-inverse)',
    itemIconColorCollapsedInverted: 'var(--gds-color-icon-neutral-light)',
    groupTextColorInverted: 'var(--gds-color-text-neutral-light3)',
    dividerColorInverted: 'var(--gds-color-border-nav-dark)'
  },
  Skeleton: {
    colorEnd: 'var(--gds-color-bg-neutral-dark1)',
    color: 'var(--gds-color-bg-neutral)'
  },
  Tree: {
    nodeColorHover: 'var(--gds-color-bg-neutral)',
    lineHeight: '1.5',
    arrowColor: 'var(--gds-color-icon-neutral)',
    nodeTextColor: 'var(--gds-color-text-neutral)',
    selectedNodeHoverColor: 'var(--gds-color-bg-primary-light2)',
    nodeColorPressed: 'var(--gds-color-bg-primary-light1)',
    nodeColorActive: 'var(--gds-color-bg-primary-light1)',
    nodeTextColorActive: 'var(--gds-color-text-primary)',
    nodeTextColorHover: 'var(--gds-color-text-neutral)',
    loadingColor: 'var(--gds-color-icon-primary)',
    dropMarkColor: 'var(--gds-color-border-primary)',
    dividerColor: 'var(--gds-color-border-neutral)',
    nodeTextColorDisabled: 'var(--gds-color-text-neutral)',
    nodeBorderRadius: 'var(--gds-border-radius-xs)',
    nodeHighlightBottomColor: 'transparent',
    lineWidth: '2px',
    nodeWrapperPadding: '0px',
    nodePadding: '5px 0',
    nodeHeight: '30px',
    fontSizeXSmall: 'var(--gds-font-size-12)',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    fontSizeXLarge: 'var(--gds-font-size-16)'
  },
  Layout: {
    headerColorInverted: 'var(--gds-color-bg-nav-dark)',
    siderBorderColor: 'var(--gds-color-border-neutral)',
    footerBorderColor: 'var(--gds-color-border-neutral)',
    headerBorderColor: 'var(--gds-color-border-neutral)',
    siderColorInverted: 'var(--gds-color-border-inverse)',
    toggleButtonColor: 'var(--gds-color-bg-button-secondary)',
    invertToggleButtonColor: 'var(--gds-color-bg-button-primary)',
    siderToggleButtonIconColorInverted: 'var(--gds-color-icon-inverse)',
    siderToggleButtonIconColor: 'var(--gds-color-icon-neutral-dark1)',
    footerColor: 'var(--gds-color-bg-light)',
    siderOverlayShadow:
      '0px 0px 1px 0px rgba(2, 13, 75, 0.30), 0px 4px 10px -2px rgba(2, 13, 75, 0.30)',
    siderResizeBarColor: 'var(--gds-color-border-primary)',
    siderResizeIconColor: 'var(--gds-color-icon-neutral)',
    siderResizeBorderColor: 'var(--gds-color-border-neutral)'
  },
  Anchor: {
    railColor: 'var(--gds-color-border-neutral)',
    railColorActive: 'var(--gds-color-border-primary)',
    linkColor: 'var(--gds-color-bg-primary-light1)',
    linkTextColor: 'var(--gds-color-text-neutral-light2)',
    linkTextColorHover: 'var(--gds-color-text-primary)',
    linkTextColorPressed: 'var(--gds-color-text-primary-dark1)',
    linkTextColorActive: 'var(--gds-color-text-primary)'
  },
  Card: {
    boxShadow:
      '0px 8px 16px -4px rgba(2, 13, 75, 0.25), 0px 0px 1px 0px rgba(2, 13, 75, 0.30)',
    borderWidth: '0',
    titleTextColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    color: 'var(--gds-color-bg-light)',
    colorModal: 'var(--gds-color-bg-light)',
    colorPopover: 'var(--gds-color-bg-light)',
    colorTarget: 'var(--gds-color-bg-primary)',
    colorEmbedded: 'var(--gds-color-bg-light)',
    colorEmbeddedCheckbox: 'var(--gds-color-bg-primary)',
    colorEmbeddedModal: 'var(--gds-color-bg-light)',
    colorEmbeddedPopover: 'var(--gds-color-bg-light)',
    colorActionArea: 'var(--gds-color-bg-light)',
    borderColor: 'var(--gds-color-border-neutral)',
    actionAreaColor: 'var(--gds-color-bg-light)',
    closeColorHover: 'var(--gds-color-bg-button-tertiary-dark1)',
    closeColorPressed: 'var(--gds-color-bg-button-tertiary-dark1)',
    closeIconColor: 'var(--gds-color-icon-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',

    // border implementation using shadow
    borderShadow:
      '0px 1px 1px 0px rgba(2, 13, 75, 0.25), 0px 0px 1px 0px rgba(2, 13, 75, 0.30)'
  },
  Dropdown: {
    // non-inverted
    optionTextColor: 'var(--gds-color-text-neutral)',
    optionTextColorHover: 'var(--gds-color-text-neutral)',
    optionTextColorActive: 'var(--gds-color-text-primary)',
    optionTextColorChildActive: 'var(--gds-color-text-primary)',
    color: 'var(--gds-color-bg-light)',
    dividerColor: 'var(--gds-color-border-neutral)',
    suffixColor: 'var(--gds-color-text-neutral)',
    prefixColor: 'var(--gds-color-text-neutral)',
    optionColorHover: 'var(--gds-color-bg-neutral-dark1)',
    optionColorActive: 'var(--gds-color-bg-primary-light1)',
    groupHeaderTextColor: 'var(--gds-color-text-neutral)',
    //  inverted
    optionTextColorInverted: 'var(--gds-color-text-neutral)',
    optionTextColorHoverInverted: 'var(--gds-color-text-neutral)',
    optionTextColorActiveInverted: 'var(--gds-color-text-primary)',
    optionTextColorChildActiveInverted: 'var(--gds-color-text-primary)',
    colorInverted: 'var(--gds-color-bg-nav-dark)',
    dividerColorInverted: 'var(--gds-color-border-neutral)',
    suffixColorInverted: 'var(--gds-color-text-neutral)',
    prefixColorInverted: 'var(--gds-color-text-neutral)',
    optionColorHoverInverted: 'var(--gds-color-bg-neutral-dark1)',
    optionColorActiveInverted: 'var(--gds-color-bg-neutral-light)',
    groupHeaderTextColorInverted: 'var(--gds-color-text-neutral)',
    optionOpacityDisabled: '0.4',
    optionIconColor: 'var(--gds-color-icon-neutral)'
  },
  Checkbox: {
    textColor: 'var(--gds-color-text-neutral)',
    border: '1.5px solid var(--gds-color-border-neutral-dark1)',
    borderHover: '1.5px solid var(--gds-color-border-neutral-dark2)',
    labelLineHeight: 'var(--gds-line-height-16)',
    colorChecked: 'var(--gds-color-bg-primary)',
    colorCheckedHover: 'var(--gds-color-bg-primary-dark1)',
    iconColor: 'var(--gds-color-icon-neutral)',
    borderRadius: 'var(--gds-border-radius-xxs)',
    borderFocus: ' 2px solid var(--gds-color-border-primary-light)',
    buttonBorderColor: 'var(--gds-color-border-neutral-dark1)',
    buttonBorderColorActive: 'var(--gds-color-border-primary)',
    buttonBorderColorHover: 'var(-gds-color-border-neutral-dark2)',
    buttonBackgroundColorActive: 'var(--gds-color-bg-primary-light1)',
    buttonBackgroundColorHover: 'var(--gds-color-bg-neutral)',
    buttonBackgroundColorHoverActive: 'var(--gds-color-bg-primary-light2)',
    buttonTextColorActive: 'var(--gds-color-text-primary)',
    buttonTextColor: 'var(--gds-color-text-neutral)'
  },
  Spinner: {
    fontSize: 'var(--gds-font-size-14)',
    invertedTextColor: 'var(--gds-color-text-inverse)',
    invertedColor: 'var(--gds-color-bg-primary)',
    invertedSecondaryColor: 'var(--gds-color-bg-neutral-dark2)',
    textColor: 'var(--gds-color-text-neutral)',
    color: 'var(--gds-color-bg-neutral)',
    secondaryColor: 'var(--gds-color-icon-neutral-dark1)',
    sizeXSmall: '22px',
    sizeSmall: '28px',
    sizeMedium: '34px',
    sizeLarge: '40px',
    sizeXLarge: '46px',
    opacitySpinning: '0',
    darkTextColor: 'var(--gds-color-text-neutral)',
    lightTextColor: 'var(--gds-color-text-light)',
    lightColor: 'var(--gds-color-bg-light)',
    scrimColor: 'rgba(2, 13, 77, 0.4)'
  },
  Progress: {
    fontSize: 'var(--gds-font-size-14)',
    fontSizeCircle: 'var(--gds-font-size-28)',
    fontWeightCircle: 400,
    railHeight: '8px',
    iconSizeCircle: '36px',
    iconSizeLine: '18px',
    iconColorPrimary: 'var(--gds-color-icon-primary)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    iconColorError: 'var(--gds-color-icon-danger)',
    textColorCircle: 'var(--gds-color-text-neutral)',
    textColorLineInner: 'var(--gds-color-text-neutral)',
    textColorLineOuter: 'var(--gds-color-text-neutral)',
    fillColorPrimary: 'var(--gds-color-bg-primary)',
    fillColorInfo: 'var(--gds-color-bg-info-dark1)',
    fillColorSuccess: 'var(--gds-color-bg-success)',
    fillColorWarning: 'var(--gds-color-bg-warning)',
    fillColorError: 'var(--gds-color-bg-danger)',
    lineBgProcessing:
      'linear-gradient(90deg, var(--gds-color-bg-neutral) 0%, var(--gds-color-bg-neutral-dark2) 100%)',
    railColor: 'var(--gds-color-bg-neutral-dark1)'
  },
  Tooltip: {
    peers: {
      Popover: {
        fontSize: 'var(--gds-font-size-12)',
        bgColor: 'var(--gds-color-bg-neutral-dark5)',
        textColor: 'var(--gds-color-text-light)',
        padding: '0.25rem 0.5rem',
        borderRadius: 'var(--gds-border-radius-xs)',
        space: '0.375rem',
        spaceArrow: '0.75rem',
        arrowOffset: '0.75rem',
        arrowOffsetVertical: '0.75rem',
        arrowHeight: '0.5rem',
        boxShadow:
          '0px 0px 1px 0px rgba(2, 13, 75, 0.30), 0px 4px 8px -2px rgba(2, 13, 75, 0.25)'
      }
    }
  },
  Avatar: {
    border: '2px solid var(--gds-color-border-neutral)',
    textColor: 'var(--gds-color-text-light)',
    iconColor: 'var(--gds-color-icon-neutral-dark1)',
    color: 'var(--gds-color-bg-primary-light1)'
  },
  Tabs: {
    dividerColor: 'var(--gds-color-border-neutral)',
    thPaddingSmall: '0.75rem 0.85rem',
    thPaddingMedium: '0.85rem 1.1rem',
    thPaddingLarge: '1rem 1.25rem',
    tdPaddingSmall: '0.75rem 0.85rem',
    tdPaddingMedium: '0.85rem 1.1rem',
    tdPaddingLarge: '1rem 1.25rem',
    sorterSize: '24px',
    tabFontSizeCard: 'var(--gds-font-size-14)',
    colorSegment: 'var(--gds-color-bg-neutral)',
    opacityDisabled: '0.4',
    // Line
    tabTextColorLine: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveLine: 'var(--gds-color-text-primary)',
    tabTextColorHoverLine: 'var(--gds-color-text-neutral)',
    tabTextColorDisabledLine: 'var(--gds-color-text-neutral-light2)',
    // Segment
    tabTextColorSegment: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveSegment: 'var(--gds-color-text-primary)',
    tabTextColorHoverSegment: 'var(--gds-color-text-neutral)',
    tabTextColorDisabledSegment: 'var(--gds-color-text-neutral-light1)',
    // Bar
    tabTextColorBar: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveBar: 'var(--gds-color-text-primary)',
    tabTextColorHoverBar: 'var(--gds-color-text-neutral)',
    tabTextColorDisabledBar: 'var(--gds-color-text-neutral-light1)',
    // Card
    tabTextColorCard: 'var(--gds-color-text-neutral-light2)',
    tabTextColorActiveCard: 'var(--gds-color-text-primary)',
    tabTextColorHoverCard: 'var(--gds-color-text-neutral)',
    tabTextColorDisabledCard: 'var(--gds-color-text-neutral-light1)',
    barColor: 'var(--gds-color-bg-tab-primary)',
    closeIconColor: 'var(--gds-color-icon-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral)',
    closeColorHover: 'var(--gds-color-bg-neutral)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark1)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    tabColorSegment: 'var(--gds-color-bg-light)',
    tabBorderColor: 'var(--gds-color-border-neutral)',
    paneTextColor: 'var(--gds-color-text-neutral-light1)',
    tabFontWeightActive: 500,
    tabFontWeight: 400,
    tabBorderRadius: 'var(--gds-border-radius-xs)',
    fontWeightStrong: 500
  },
  Radio: {
    labelLineHeight: '1.6',
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    textColor: 'var(--gds-color-text-neutral)',
    dotColorActive: 'var(--gds-color-bg-primary)',
    dotColorDisabled: 'var(--gds-color-bg-primary)',
    dotColorHoverActive: 'var(--gds-color-bg-primary-dark1)',
    opacityDisabled: '40%',
    boxShadow: 'inset 0 0 0 2px var(--gds-color-bg-neutral-dark2)',
    boxShadowActive: 'inset 0 0 0 2px var(--gds-color-bg-primary)',
    boxShadowActiveHover: 'inset 0 0 0 2px var(--gds-color-icon-info-dark2)',
    boxShadowHover: 'inset 0 0 0 2px var(--gds-color-border-neutral-dark3)',
    boxShadowDisabled: 'inset 0 0 0 2px var(--gds-color-bg-neutral-light)',
    boxShadowFocus:
      'inset 0 0 0 2px var(--gds-color-bg-primary), 0 0 0 2px var(--gds-color-bg-primary)',
    buttonBackgroundColorHoverActive: 'var(--gds-color-bg-primary-light1)',
    buttonTextColor: 'var(--gds-color-text-neutral-light1)',
    buttonBorderColor: 'var(--gds-color-border-neutral-dark2)',
    buttonBorderColorActive: 'var(--gds-color-border-primary-light)',
    buttonBorderColorHover: 'var(--gds-color-border-neutral-dark3)',
    buttonBackgroundColorActive: 'var(--gds-color-bg-primary-light2)',
    buttonBackgroundColorHover: 'var(--gds-color-bg-neutral)',
    buttonTextColorHover: 'var(--gds-color-text-primary)',
    buttonBorderRadius: 'var(--gds-border-radius-xs)',
    buttonTextColorActive: 'var(--gds-color-text-primary)',
    buttonBoxShadowFocus: 'inset 0 0 0 2px var(--gds-color-bg-primary)',
    iconColor: 'var(--gds-color-icon-primary)',
    iconSelectedColor: 'var(--gds-color-icon-primary)'
  },
  Drawer: {
    bodyPadding: '16px 24px',
    headerPadding: '16px 24px',
    footerPadding: '24px 24px',
    color: 'var(--gds-color-bg-neutral)',
    textColor: 'var(--gds-color-text-neutral-light1)',
    closeIconColor: 'var(--gds-color-icon-neutral-dark1)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    descriptionTextColor: 'var(--gds-color-text-neutral-light2)',
    titleFontSize: 'var(--gds-font-size-20)',
    headerBorderBottom: '1px solid var(--gds-color-border-neutral)',
    footerBorderTop: '1px solid var(--gds-color-border-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    closeSize: '36px',
    closeIconSize: '20px',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    closeColorHover: 'var(--gds-color-bg-neutral-dark1)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark2)',
    resizableTriggerColorHover: 'var(--gds-color-bg-primary-dark1)',
    titleFontWeight: 500,
    lineHeight: '1.6'
  },
  Button: {
    iconColor: 'var(--gds-color-icon-neutral-dark1)',
    border: '1px solid var(--gds-color-border-button-secondary)',
    borderHover: '1px solid var(--gds-color-border-button-secondary)',
    borderPressed: '1px solid var(--gds-color-border-button-secondary-dark2)',
    borderFocus: '2px solid var(--gds-color-border-primary-light)',
    borderDisabled: '1px solid var(--gds-color-border-button-secondary)',
    borderNeutral: '1px solid var(--gds-color-border-button-secondary)',
    borderHoverNeutral: '1px solid var(--gds-color-border-button-secondary)',
    borderPressedNeutral:
      '1px solid var(--gds-color-border-button-secondary-dark2)',
    borderFocusNeutral: '2px solid var(--gds-color-border-primary-light)',
    borderDisabledNeutral: '1px solid var(--gds-color-border-button-secondary)',
    borderPrimary: '1px solid var(--gds-color-border-primary)',
    borderHoverPrimary: '1px solid var(--gds-color-border-primary)',
    borderPressedPrimary: '1px solid var(--gds-color-border-primary)',
    borderFocusPrimary: '2px solid var(--gds-color-border-primary-light)',
    borderDisabledPrimary: '1px solid var(--gds-color-border-primary)',
    borderInfo: '1px solid var(--gds-color-border-info-dark1)',
    borderHoverInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderPressedInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderFocusInfo: '1px solid var(--gds-color-bg-info-dark1)',
    borderDisabledInfo: '1px solid var(--gds-color-bg-info-dark1)',

    borderSuccess: '1px solid var(--gds-color-border-success)',
    borderHoverSuccess: '1px solid var(--gds-color-border-success)',
    borderPressedSuccess: '1px solid var(--gds-color-border-success)',
    borderFocusSuccess: '2px solid var(--gds-color-border-success)',
    borderDisabledSuccess: '1px solid var(--gds-color-border-success)',
    borderWarning: '1px solid var(--gds-color-border-warning)',
    borderHoverWarning: '1px solid var(--gds-color-border-warning)',
    borderPressedWarning: '1px solid var(--gds-color-border-warning)',
    borderFocusWarning: '2px solid var(--gds-color-border-warning)',
    borderDisabledWarning: '1px solid var(--gds-color-border-warning)',
    borderError: '1px solid var(--gds-color-border-button-danger-secondary)',
    borderHoverError:
      '1px solid var(--gds-color-border-button-danger-secondary)',
    borderPressedError:
      '1px solid var(--gds-color-border-button-danger-secondary)',
    borderFocusError:
      '2px solid var(--gds-color-border-button-danger-secondary)',
    borderDisabledError:
      '1px solid var(--gds-color-border-button-danger-secondary)',
    // text color
    // filled
    textColorFilled: 'var(--gds-color-text-button-primary)',
    iconColorFilled: 'var(--gds-color-icon-inverse)',
    textColorHoverFilled: 'var(--gds-color-text-button-primary)',
    textColorPressedFilled: 'var(--gds-color-text-button-primary)',
    textColorFocusFilled: 'var(--gds-color-text-button-primary)',
    textColorDisabledFilled: 'var(--gds-color-text-button-primary)',
    textColorFilledNeutral: 'var(--gds-color-text-button-primary)',
    iconColorFilledNeutral: 'var(--gds-color-icon-inverse)',
    textColorHoverFilledNeutral: 'var(--gds-color-text-button-primary)',
    textColorPressedFilledNeutral: 'var(--gds-color-text-button-primary)',
    textColorFocusFilledNeutral: 'var(--gds-color-text-button-primary)',
    textColorDisabledFilledNeutral: 'var(--gds-color-text-button-primary)',
    textColorFilledPrimary: 'var(--gds-color-text-button-primary)',
    iconColorFilledPrimary: 'var(--gds-color-icon-inverse)',
    textColorHoverFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorPressedFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorFocusFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorDisabledFilledPrimary: 'var(--gds-color-text-button-primary)',
    textColorFilledInfo: 'var(--gds-color-text-button-primary)',
    iconColorFilledInfo: 'var(--gds-color-icon-inverse)',
    textColorHoverFilledInfo: 'var(--gds-color-text-button-primary))',
    textColorPressedFilledInfo: 'var(--gds-color-text-button-primary))',
    textColorFocusFilledInfo: 'var(--gds-color-text-button-primary))',
    textColorDisabledFilledInfo: 'var(--gds-color-text-button-primary))',
    textColorFilledSuccess: 'var(--gds-color-text-button-primary)',
    iconColorFilledSuccess: 'var(--gds-color-icon-inverse)',
    textColorHoverFilledSuccess: 'var(--gds-color-text-button-primary)',
    textColorPressedFilledSuccess: 'var(--gds-color-text-button-primary)',
    textColorFocusFilledSuccess: 'var(--gds-color-text-button-primary)',
    textColorDisabledFilledSuccess: 'var(--gds-color-text-button-primary)',
    textColorFilledWarning: 'var(--gds-color-text-button-primary)',
    iconColorFilledWarning: 'var(--gds-color-icon-inverse)',
    textColorHoverFilledWarning: 'var(--gds-color-text-button-primary)',
    textColorPressedFilledWarning: 'var(--gds-color-text-button-primary)',
    textColorFocusFilledWarning: 'var(--gds-color-text-button-primary)',
    textColorDisabledFilledWarning: 'var(--gds-color-text-button-primary)',
    textColorFilledError: 'var(--gds-color-text-button-danger-primary)',
    iconColorFilledError: 'var(--gds-color-icon-inverse)',
    textColorHoverFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorPressedFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorFocusFilledError: 'var(--gds-color-text-button-danger-primary)',
    textColorDisabledFilledError: 'var(--gds-color-text-button-danger-primary)',
    // // link & Text type text color
    iconColorText: 'var(--gds-color-icon-neutral)',
    textColorText: 'var(--gds-color-text-button-tertiary)',
    textColorTextHover: 'var(--gds-color-text-button-tertiary)',
    textColorTextPressed: 'var(--gds-color-text-button-tertiary)',
    textColorTextFocus: 'var(--gds-color-text-button-tertiary)',
    textColorTextDisabled: 'var(--gds-color-text-button-tertiary)',
    iconColorTextPrimary: 'var(--gds-color-icon-primary)',
    textColorTextPrimary: 'var(--gds-color-text-primary)',
    textColorTextHoverPrimary: 'var(--gds-color-text-primary)',
    textColorTextPressedPrimary: 'var(--gds-color-text-primary)',
    textColorTextFocusPrimary: 'var(--gds-color-text-primary)',
    textColorTextDisabledPrimary: 'var(--gds-color-text-primary)',
    iconColorTextInfo: 'var(--gds-color-icon-info)',
    textColorTextInfo: 'var(--gds-color-text-info)',
    textColorTextHoverInfo: 'var(--gds-color-text-info)',
    textColorTextPressedInfo: 'var(--gds-color-text-info)',
    textColorTextFocusInfo: 'var(--gds-color-text-info)',
    textColorTextDisabledInfo: 'var(--gds-color-text-info)',
    iconColorTextNeutral: 'var(--gds-color-icon-neutral)',
    textColorTextNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextHoverNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextPressedNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextFocusNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorTextDisabledNeutral: 'var(--gds-color-text-button-tertiary)',
    iconColorTextSuccess: 'var(--gds-color-icon-success)',
    textColorTextSuccess: 'var(--gds-color-text-success)',
    textColorTextHoverSuccess: 'var(--gds-color-text-success)',
    textColorTextPressedSuccess: 'var(--gds-color-text-success)',
    textColorTextFocusSuccess: 'var(--gds-color-text-success)',
    textColorTextDisabledSuccess: 'var(--gds-color-text-success)',
    iconColorTextError: 'var(--gds-color-icon-danger)',
    textColorTextError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextHoverError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextPressedError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextFocusError: 'var(--gds-color-text-button-danger-tertiary)',
    textColorTextDisabledError: 'var(--gds-color-text-button-danger-tertiary)',
    iconColorTextWarning: 'var(--gds-color-icon-warning)',
    textColorTextWarning: 'var(--gds-color-text-warning)',
    textColorTextHoverWarning: 'var(--gds-color-text-warning)',
    textColorTextPressedWarning: 'var(--gds-color-text-warning)',
    textColorTextFocusWarning: 'var(--gds-color-text-warning)',
    textColorTextDisabledWarning: 'var(--gds-color-text-warning)',
    // // outlined text color
    textColorOutlinedPrimary: 'var(--gds-color-text-primary)',
    iconColorOutlinedPrimary: 'var(--gds-color-icon-primary)',
    textColorOutlinedNeutral: 'var(--gds-color-text-button-secondary)',
    iconColorOutlinedNeutral: 'var(--gds-color-icon-neutral)',
    textColorOutlinedInfo: 'var(--gds-color-text-info)',
    iconColorOutlinedInfo: 'var(--gds-color-icon-info)',
    textColorOutlinedSuccess: 'var(--gds-color-text-success)',
    iconColorOutlinedSuccess: 'var(--gds-color-icon-success)',
    textColorOutlinedError: 'var(--gds-color-text-button-danger-secondary)',
    iconColorOutlinedError: 'var(--gds-color-icon-danger)',
    textColorOutlinedWarning: 'var(--gds-color-text-warning)',
    iconColorOutlinedWarning: 'var(--gds-color-icon-warning)',

    // subtle or text text color
    textColorTertiaryPrimary: 'var(--gds-color-text-primary)',
    iconColorTertiaryPrimary: 'var(--gds-color-icon-primary)',
    textColorTertiaryNeutral: 'var(--gds-color-text-button-tertiary)',
    iconColorTertiaryNeutral: 'var(--gds-color-icon-neutral)',
    textColorTertiaryInfo: 'var(--gds-color-text-info)',
    iconColorTertiaryInfo: 'var(--gds-color-icon-info)',
    textColorTertiarySuccess: 'var(--gds-color-text-success)',
    iconColorTertiarySuccess: 'var(--gds-color-icon-success)',
    textColorTertiaryError: 'var(--gds-color-text-button-danger-tertiary)',
    iconColorTertiaryError: 'var(--gds-color-icon-danger)',
    textColorTertiaryWarning: 'var(--gds-color-text-warning)',
    iconColorTertiaryWarning: 'var(--gds-color-icon-warning)',
    // // other text color
    textColor: 'var(--gds-color-text-button-secondary)',
    textColorHover: 'var(--gds-color-text-button-secondary)',
    textColorPressed: 'var(--gds-color-text-button-secondary)',
    textColorFocus: 'var(--gds-color-text-button-secondary)',
    textColorDisabled: 'var(--gds-color-text-button-secondary)',
    textColorNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorHoverNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorPressedNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorFocusNeutral: 'var(--gds-color-text-button-tertiary)',
    textColorDisabledNeutral: 'var(--gds-color-text-button-tertiary)',
    // backgroundColor
    // primary
    colorPrimary: 'var(--gds-color-bg-button-primary)',
    colorHoverPrimary: 'var(--gds-color-bg-button-primary-dark1)',
    colorPressedPrimary: 'var(--gds-color-bg-button-primary-dark2)',
    colorFocusPrimary: 'var(--gds-color-bg-button-primary)',
    colorDisabledPrimary: 'var(--gds-color-bg-button-primary)',
    // info
    colorInfo: 'var(--gds-color-bg-info)',
    colorHoverInfo: 'var(--gds-color-bg-info-dark1)',
    colorPressedInfo: 'var(--gds-color-bg-info-dark2)',
    colorFocusInfo: 'var(--gds-color-bg-info)',
    colorDisabledInfo: 'var(--gds-color-bg-info)',
    // error
    colorError: 'var(--gds-color-bg-button-danger-primary)',
    colorHoverError: 'var(--gds-color-bg-button-danger-primary-dark1)',
    colorPressedError: 'var(--gds-color-bg-button-danger-primary-dark2)',
    colorFocusError: 'var(--gds-color-bg-button-danger-primary)',
    colorDisabledError: 'var(--gds-color-bg-button-danger-primary)',
    // success
    colorSuccess: 'var(--gds-color-bg-success)',
    colorHoverSuccess: 'var(--gds-color-bg-success-dark1)',
    colorPressedSuccess: 'var(--gds-color-bg-success-dark2)',
    colorFocusSuccess: 'var(--gds-color-bg-success)',
    colorDisabledSuccess: 'var(--gds-color-bg-success)',
    // warning
    colorWarning: 'var(--gds-color-bg-warning)',
    colorHoverWarning: 'var(--gds-color-bg-warning-dark1)',
    colorPressedWarning: 'var(--gds-color-bg-warning-dark2)',
    colorFocusWarning: 'var(--gds-color-bg-warning)',
    colorDisabledWarning: 'var(--gds-color-bg-warning)',

    // outlined
    colorOutlinedError: 'var(--gds-color-bg-button-danger-secondary)',
    colorOutlinedHoverError:
      'var(--gds-color-bg-button-danger-secondary-dark1)',
    colorOutlinedPressedError:
      'var(--gds-color-bg-button-danger-secondary-dark2)',
    colorOutlinedFocusError: 'var(--gds-color-bg-button-danger-secondary)',

    // subtle
    colorSubtleHoverError: 'var(--gds-color-bg-button-danger-tertiary-dark1)',
    colorSubtlePressedError: 'var(--gds-color-bg-button-danger-tertiary-dark2)',
    colorSubtleFocusError: 'none',

    // bg-color
    colorDefault: 'var(--gds-color-bg-button-secondary)',
    colorDisabledNeutral: 'var(--gds-color-bg-button-secondary)',
    colorFocusNeutral: 'var(--gds-color-bg-button-secondary)',
    colorPressed: 'var(--gds-color-bg-button-secondary-dark2)',
    colorPressedNeutral: 'var(--gds-color-bg-button-primary-dark2)',
    colorQuaternaryHover: 'var(--gds-color-bg-button-secondary-dark1)',
    colorQuaternaryPressed: 'var(--gds-color-bg-button-secondary-dark2)',
    borderRadiusXSmall: 'var(--gds-border-radius-xs)',
    borderRadiusSmall: 'var(--gds-border-radius-s)',
    borderRadiusMedium: 'var(--gds-border-radius-m)',
    borderRadiusLarge: 'var(--gds-border-radius-l)',
    borderRadiusXLarge: 'var(--gds-border-radius-xl)',
    colorSecondary: 'var(--gds-color-bg-button-secondary)',
    focusColor: 'var(--gds-color-bg-button-secondary)',
    linkColorActive: 'var(--gds-color-bg-button-secondary-dark1)',
    linkColorHover: 'var(--gds-color-bg-button-secondary-dark1)',
    linkColorPressed: 'var(--gds-color-bg-button-secondary-dark2)',
    rippleColor: 'var(--gds-color-bg-button-secondary-dark2)',
    rippleColorError: 'var(--gds-color-bg-button-danger-primary-dark2)',
    rippleColorNeutral: 'var(--gds-color-bg-button-secondary-dark2)',
    rippleColorPrimary: 'var(--gds-color-bg-button-primary-dark2)',
    rippleDuration: '0s'
  },
  Notification: {
    titleFontSize: 'var(--gds-font-size-14)',
    metaFontSize: 'var(--gds-font-size-12)',
    descriptionFontSize: 'var(--gds-font-size-14)',
    lineHeight: 'var(--gds-line-height-20)',
    borderRadius: 'var(--gds-border-radius-xs)',
    fontSize: 'var(--gds-font-size-14)',
    headerFontWeight: 500,
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    color: 'var(--gds-color-bg-light)',
    colorSuccess: 'var(--gds-color-bg-success-light2)',
    colorInfo: 'var(--gds-color-bg-info-light2)',
    colorWarning: 'var(--gds-color-bg-warning-light2)',
    colorError: 'var(--gds-color-bg-danger-light2)',
    iconColorError: 'var(--gds-color-icon-danger)',
    textColor: 'var(--gds-color-text-neutral)',
    closeIconColor: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    closeColorHover: 'var(--gds-color-bg-neutral)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    descriptionTextColor: 'var(--gds-color-text-neutral-light1)',
    actionTextColor: 'var(--gds-color-text-neutral)'
  },
  PageHeader: {
    fontSize: 'var(--gds-font-size-14)',
    titleTextColorInverted: 'var(--gds-color-text-light)',
    backColorInverted: 'var(--gds-color-icon-inverse)',
    backColorHoverInverted: 'var(--gds-color-icon-inverse-dark1)',
    backColorPressedInverted: 'var(--gds-color-icon-inverse-dark2)',
    descriptionTextColorInverted: 'var(--gds-color-text-inverse)',
    titleFontWeight: 500,
    titleTextColor: 'var(--gds-color-text-neutral)',
    backColor: 'var(--gds-color-icon-neutral)',
    backColorHover: 'var(--gds-color-icon-neutral-dark1)',
    backColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    descriptionTextColor: 'var(--gds-color-text-neutral-light2)'
  },
  Accordion: {
    dividerColor: 'var(--gds-color-border-neutral)',
    textColor: 'var(--gds-color-text-neutral)',
    contentColor: 'var(--gds-color-text-neutral-light2)',
    arrowColor: 'var(--gds-color-icon-neutral)',
    boxedBgColor: 'var(--gds-color-bg-light)',
    hoverColor: 'var(--gds-color-bg-neutral)',
    activeColor: 'var(--gds-color-bg-neutral)',
    fontSize: 'var(--gds-font-size-14)',
    titleFontSize: 'var(--gds-font-size-16)',
    arrowBgColor: 'transparent',
    arrowActiveColor: 'var(--gds-color-icon-neutral-dark1)',
    disabledOpacity: '0.4'
  },
  Timeline: {
    contentFontSize: 'var(--gds-font-size-14)',
    titleFontWeight: 500,
    circleBorder: '2px solid var(--gds-color-icon-neutral)',
    circleBorderNeutral: '2px solid  var(--gds-color-icon-neutral)',
    circleBorderInfo: '2px solid var(--gds-color-icon-info)',
    circleBorderError: '2px solid var(--gds-color-icon-danger)',
    circleBorderSuccess: '2px solid var(--gds-color-icon-success)',
    circleBorderWarning: '2px solid var(--gds-color-icon-warning)',
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorNeutral: 'var(--gds-color-icon-neutral)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorError: 'var(--gds-color-icon-danger)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    contentTextColor: 'var(--gds-color-text-neutral-light1)',
    metaTextColor: 'var(--gds-color-text-neutral-light2)',
    lineColor: 'var(--gds-color-border-neutral-dark1)'
  },
  InternalSelection: {
    textColor: 'var(--gds-color-text-neutral)',
    textColorDisabled: changeColor('#020D4D', { alpha: 0.6 }),
    placeholderColor: 'var(--gds-color-text-neutral-light3)',
    placeholderColorDisabled: changeColor('#9DA2BF', { alpha: 0.6 }),
    arrowColor: 'var(--gds-color-icon-neutral)',
    arrowColorDisabled: changeColor('#7D83A6', { alpha: 0.6 }),
    caretColor: 'var(--gds-color-text-neutral-light3)',
    color: 'var(--gds-color-bg-base)',
    colorHover: 'var(--gds-color-bg-base)',
    colorActive: 'var(--gds-color-bg-base)',
    colorDisabled: changeColor('#F6F7FA', { alpha: 0.6 }),
    colorActiveWarning: 'var(--gds-color-bg-base)',
    colorActiveError: 'var(--gds-color-bg-base)',
    boxShadowHover: 'none',
    boxShadowHoverWarning: 'none',
    boxShadowHoverError: 'none',
    border: '1px solid var(--gds-color-border-neutral-dark1)',
    borderDisabled: `1px solid ${changeColor('#7D83A6', { alpha: 0.6 })}`,
    borderHover: '1px solid var(--gds-color-border-neutral-dark3)',
    borderActive: '1px solid var(--gds-color-border-primary)',
    borderFocus: '1px solid var(--gds-color-border-primary)',
    clearColor: 'var(--gds-color-icon-neutral)',
    clearColorHover: 'var(--gds-color-icon-neutral)',
    clearColorPressed: 'var(--gds-color-icon-neutral)',
    paddingSingle: '0 36px 0px 8px',
    paddingMultiple: '3px 36px 3px 8px'
  },
  InternalSelectMenu: {
    optionTextColor: 'var(--gds-color-text-neutral)',
    optionTextColorPressed: 'var(--gds-color-text-neutral-light3)',
    optionTextColorDisabled: changeColor('#020D4D', { alpha: 0.4 }),
    optionTextColorActive: 'var(--gds-color-text-neutral)',
    optionColorPending: 'var(--gds-color-bg-neutral-dark1)',
    optionColorActive: 'var(--gds-color-bg-neutral-dark1)',
    optionColorActivePending: 'var(--gds-color-bg-neutral-dark1)',
    groupHeaderTextColor: 'var(--gds-color-text-neutral-light1)',
    actionDividerColor: 'var(--gds-color-border-neutral)',
    optionOpacityDisabled: '0.4'
  },
  Dialog: {
    titleTextColor: 'var(--gds-color-text-neutral)',
    titleFontWeight: '500',
    textColor: 'var(--gds-color-text-neutral-light2)',
    closeColorHover: 'var(--gds-color-bg-neutral-dark1)',
    closeColorPressed: 'var(--gds-color-bg-neutral-dark2)',
    closeIconColor: 'var(--gds-color-icon-neutral)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    borderRadius: 'var(--gds-border-radius-m)'
  },
  Breadcrumb: {
    itemTextColor: 'var(--gds-color-text-info)',
    itemTextColorHover: 'var(--gds-color-text-info-dark1)',
    itemTextColorPressed: 'var(--gds-color-text-info-dark2)',
    itemTextColorActive: 'var(--gds-color-text-neutral)',
    itemColorHover: 'transparent',
    itemColorPressed: 'transparent',
    separatorColor: 'var(--gds-color-icon-neutral)',
    separatorPadding: '0 4px',
    itemLineHeight: 'var(--gds-line-height-16)'
  },
  Code: {
    lineNumberBackgroundColor: 'var(--gds-color-bg-neutral-dark1)',
    textColor: 'var(--gds-color-text-neutral)',
    lineNumberTextColor: 'var(--gds-color-text-neutral-light2)',
    'mono-3': 'var(--gds-color-text-neutral-light1)',
    'hue-1': '#0B8EC9',
    'hue-2': '#BE304A',
    'hue-3': '#C12984',
    'hue-4': 'var(--gds-color-text-success)',
    'hue-5': '#263EB3',
    'hue-5-2': '#8B1E31',
    'hue-6': '#A45B14',
    'hue-6-2': '#C12984'
  },
  DataTable: {
    actionDividerColor: 'var(--gds-color-border-neutral)',
    borderColor: 'var(--gds-color-border-neutral)',
    tdColorHover: 'var(--gds-color-bg-neutral-light)',
    tdColorStriped: 'var(--gds-color-bg-neutral-dark1)',
    thColor: 'var(--gds-color-bg-base)',
    thDescriptionTextColor: 'var(--gds-color-text-neutral-light2)',
    thColorHover: 'var(--gds-color-bg-neutral-light)',
    tdColorDisabled: 'var(--gds-color-bg-light)',
    tdColor: 'var(--gds-color-bg-base)',
    tdTextColor: 'var(--gds-color-text-neutral-light1)',
    thTextColor: 'var(--gds-color-text-neutral)',
    thButtonColorHover: '#DEE0EC',
    thIconColor: 'var(--gds-color-icon-neutral)',
    thIconColorActive: 'var(--gds-color-icon-primary)',
    trBackgroundColorSelected: 'var(--gds-color-bg-primary-light2)',
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    // modal
    borderColorModal: 'var(--gds-color-border-neutral)',
    tdColorHoverModal: 'var(--gds-color-bg-neutral-dark2)',
    tdColorStripedModal: 'var(--gds-color-bg-neutral-dark1)',
    thColorModal: 'var(--gds-color-bg-neutral-dark2)',
    thColorHoverModal: 'var(--gds-color-bg-neutral-dark2)',
    tdColorModal: 'var(--gds-color-bg-light)',
    // popover
    borderColorPopover: 'var(--gds-color-border-neutral)',
    tdColorHoverPopover: 'var(--gds-color-bg-neutral-dark2)',
    tdColorStripedPopover: 'var(--gds-color-bg-neutral-dark1)',
    thColorPopover: 'var(--gds-color-bg-neutral-dark2)',
    thColorHoverPopover: 'var(--gds-color-bg-neutral-dark2)',
    tdColorPopover: 'var(--gds-color-bg-light)',
    boxShadowBefore: 'inset -12px 0 8px -12px rgba(0, 0, 0, .18)',
    boxShadowAfter: 'inset 12px 0 8px -12px rgba(0, 0, 0, .18)',
    expandedBackgroundColor: 'var(--gds-color-bg-neutral)',
    tableColorHover: '#F1F2F9'
  },
  Table: {
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)'
  },
  Empty: {
    titleTextColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral-light2)',
    actionsTextColor: 'var(--gds-color-text-neutral-light1)',
    iconColor: 'var(--gds-color-icon-neutral)',
    iconSizeSmall: '64px',
    iconSizeMedium: '96px',
    iconSizeLarge: '100px',
    iconSizeXLarge: '125px',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    fontSizeXLarge: 'var(--gds-font-size-18)',
    titleFontSizeSmall: 'var(--gds-font-size-16)',
    titleFontSizeMedium: 'var(--gds-font-size-16)',
    titleFontSizeLarge: 'var(--gds-font-size-18)',
    titleFontSizeXLarge: 'var(--gds-font-size-24)',
    descriptionFontSizeSmall: 'var(--gds-font-size-14)',
    descriptionFontSizeMedium: 'var(--gds-font-size-14)',
    descriptionFontSizeLarge: 'var(--gds-font-size-16)',
    descriptionFontSizeXLarge: 'var(--gds-font-size-14)'
  },
  Result: {
    lineHeight: 'var(--gds-line-height-16)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    iconSizeMedium: '96px',
    textColor: 'var(--gds-color-text-neutral-light2)',
    iconColorError: 'var(--gds-color-icon-danger)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorWarning: 'var(--gds-color-icon-warning)'
  },
  Typography: {
    fontHeading1Sb: 'var(--gds-font-heading-1-sb)',
    fontHeading2Sb: 'var(--gds-font-heading-2-sb)',
    fontHeading3M: 'var(--gds-font-heading-3-m)',
    fontHeading4R: 'var(--gds-font-heading-4-r)',
    fontHeading4M: 'var(--gds-font-heading-4-m)',
    fontHeading5M: 'var(--gds-font-heading-5-m)',
    fontHeading6R: 'var(--gds-font-heading-6-r)',
    fontHeading6M: 'var(--gds-font-heading-6-m)',

    letterSpacingHeading1Sb: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading2Sb: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading3M: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading4R: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading4M: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading5M: 'var(--gds-letter-spacing-0)',
    letterSpacingHeading6R: 'var(--gds-letter-spacing-1)',
    letterSpacingHeading6M: 'var(--gds-letter-spacing-2)',

    fontParagraph1R: 'var(--gds-font-paragraph-1-r)',
    fontParagraph1M: 'var(--gds-font-paragraph-1-m)',
    fontParagraph2R: 'var(--gds-font-paragraph-2-r)',
    fontParagraph2M: 'var(--gds-font-paragraph-2-m)',
    fontParagraph3R: 'var(--gds-font-paragraph-3-r)',
    fontParagraph3M: 'var(--gds-font-paragraph-3-m)',

    fontCode1R: 'var(--gds-font-code-1-r)',

    fontBody1R: 'var(--gds-font-body-1-r)',
    fontBody1M: 'var(--gds-font-body-1-m)',
    fontBody2R: 'var(--gds-font-body-2-r)',
    fontBody2M: 'var(--gds-font-body-2-m)',
    fontBody3R: 'var(--gds-font-body-3-r)',
    fontBody3M: 'var(--gds-font-body-3-m)',
    fontBody4R: 'var(--gds-font-body-4-r)',
    fontBody4M: 'var(--gds-font-body-4-m)',
    fontBody5M: 'var(--gds-font-body-5-m)',
    fontBody5R: 'var(--gds-font-body-5-r)',

    fontLabel1R: 'var(--gds-font-label-1-r)',
    fontLabel1M: 'var(--gds-font-label-1-m)',
    fontLabel2R: 'var(--gds-font-label-2-r)',
    fontLabel2M: 'var(--gds-font-label-2-m)',

    fontLink1R: 'var(--gds-font-link-1-r)',
    fontLink1M: 'var(--gds-font-link-1-m)',
    fontLink2R: 'var(--gds-font-link-2-r)',
    fontLink2M: 'var(--gds-font-link-2-m)',
    fontLink3R: 'var(--gds-font-link-3-r)',
    fontLink3M: 'var(--gds-font-link-3-m)',

    aTextColor: 'var(--gds-color-text-info)',
    headingFontSize1: 'var(--gds-font-size-32)',
    headingFontSize2: 'var(--gds-font-size-24)',
    headingFontSize3: 'var(--gds-font-size-20)',
    headingFontSize4: 'var(--gds-font-size-18)',
    headingFontSize5: 'var(--gds-font-size-16)',
    headingFontSize6: 'var(--gds-font-size-14)',
    headingLineHeight: '1.2',
    liLineHeight: '1.6',
    liFontSize: 'var(--gds-font-size-14)',
    headerFontWeight: 500,
    blockquoteLineHeight: '1.6',
    blockquoteFontSize: 'var(--gds-font-size-14)',
    codeBorderRadius: '2px',
    pLineHeight: '1.6',
    pFontSize: 'var(--gds-font-size-14)',
    labelTextColor: 'var(--gds-color-text-neutral)',
    titleTextColor: 'var(--gds-color-text-neutral)',
    blockquoteTextColor: 'var(--gds-color-text-neutral)',
    blockquotePrefixColor: 'var(--gds-color-border-neutral)',
    liTextColor: 'var(--gds-color-text-neutral)',
    hrColor: 'var(--gds-color-border-neutral)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    pTextColor: 'var(--gds-color-text-neutral)',
    pTextColor1Depth: 'var(--gds-color-text-neutral)',
    pTextColor2Depth: 'var(--gds-color-text-neutral)',
    pTextColor3Depth: 'var(--gds-color-text-neutral)',
    headingBarColor: 'var(--gds-color-bg-primary)',
    headingBarColorPrimary: 'var(--gds-color-bg-primary)',
    headingBarColorInfo: 'var(--gds-color-bg-info)',
    headingBarColorError: 'var(--gds-color-bg-danger)',
    headingBarColorWarning: 'var(--gds-color-bg-warning)',
    headingBarColorSuccess: 'var(--gds-color-bg-success)',
    textColor: 'var(--gds-color-text-neutral)',
    textColor1Depth: 'var(--gds-color-text-neutral)',
    textColor2Depth: 'var(--gds-color-text-neutral)',
    textColor3Depth: 'var(--gds-color-text-neutral)',
    textColorPrimary: 'var(--gds-color-text-primary)',
    textColorInfo: 'var(--gds-color-text-info)',
    textColorSuccess: 'var(--gds-color-text-success)',
    textColorWarning: 'var(--gds-color-text-warning)',
    textColorError: 'var(--gds-color-text-danger)',
    textColorInherit: 'inherit',
    codeTextColor: 'var(--gds-color-text-neutral)',
    codeColor: 'var(--gds-color-bg-neutral-light)',
    opacity1: '0.82',
    opacity2: '0.72',
    opacity3: '0.38',
    opacity4: '0.24',
    opacity5: '0.18',
    codeBorder: '1px solid var(--gds-color-border-neutral)'
  },
  JsonViewer: {
    borderColor: 'var(--gds-color-border-neutral)',
    backgroundColor: 'var(--gds-color-bg-light)',
    lineNumberbackgroundColor: 'var(--gds-color-bg-neutral-light)',
    fontSizeXLarge: 'var(--gds-font-size-16)',
    fontSize: 'var(--gds-font-size-14)',
    borderRadius: 'var(--gds-border-radius-m)',
    lineNumberTextColor: 'var(--gds-color-text-neutral-light2)',
    copyIconColor: 'var(--gds-color-icon-neutral-dark1)',
    chevronIconColor: 'var(--gds-color-icon-neutral)',
    bracketColor: 'var(--gds-color-text-neutral)',
    keyColor: 'var(--gds-color-text-support-violet-light)',
    numberValueColor: 'var(--gds-color-text-warning)',
    stringValueColor: 'var(--gds-color-text-success)',
    nullvalueColor: 'var(--gds-color-text-neutral-light2)',
    booleanValueColor: 'var(--gds-color-text-primary)',
    undefinedValueColor: 'var(--gds-color-text-neutral-light2)',
    scrollbarColor: 'var(--gds-color-bg-neutral-dark2)',
    commentColor: 'var(--gds-color-text-warning)',
    optionColor: 'var(--gds-color-text-info)',

    borderColorDark: 'var(--gds-color-border-nav-dark)',
    backgroundColorDark: 'var(--gds-color-bg-neutral-dark5)',
    lineNumberbackgroundColorDark: 'var(--gds-color-bg-neutral-light-dark)',
    lineNumberTextColorDark: 'var(--gds-color-icon-neutral-light-dark1)',
    copyIconColorDark: 'var(--gds-color-icon-neutral-light-dark1)',
    chevronIconColorDark: 'var(--gds-color-icon-neutral-dark)',
    bracketColorDark: 'var(--gds-color-text-neutral-dark)',
    keyColorDark: 'var(--gds-color-text-violet-dark)',
    numberValueColorDark: 'var(--gds-color-text-warning-dark)',
    booleanValueColorDark: 'var(--gds-color-text-primary)',
    undefinedValueColorDark: 'var(--gds-color-text-neutral-dark)',
    stringValueColorDark: 'var(--gds-color-text-success-dark)',
    nullvalueColorDark: 'var(--gds-color-text-neutral-dark)',
    scrollbarColorDark: 'var(--gds-color-bg-neutral-light-dark)',
    commentColorDark: 'var(--gds-color-text-warning-dark)',
    optionColorDark: 'var(--gds-color-text-info-dark)'
  },
  DatePicker: {
    itemFontSize: 'var(--gds-font-size-14)',
    calendarDaysFontSize: 'var(--gds-font-size-14)',
    calendarTitleFontSize: 'var(--gds-font-size-14)',
    itemTextColor: 'var(--gds-color-text-neutral)',
    itemTextColorDisabled: 'var(--gds-color-text-neutral-light3)',
    itemTextColorActive: 'var(--gds-color-text-light)',
    itemTextColorCurrent: 'var(--gds-color-text-primary)',
    itemColorIncluded: 'var(--gds-color-bg-primary-light1)',
    itemColorHover: 'var(--gds-color-bg-primary-light1)',
    itemColorDisabled: 'var(--gds-color-bg-primary-light1)',
    itemColorActive: 'var(--gds-color-text-primary)',
    itemBorderRadius: 'var(--gds-border-radius-xs)',
    panelColor: 'var(--gds-color-bg-light)',
    panelTextColor: 'var(--gds-color-text-neutral)',
    arrowColor: 'var(--gds-color-icon-neutral)',
    calendarTitleTextColor: 'var(--gds-color-text-neutral)',
    calendarTitleColorHover: 'var(--gds-color-bg-primary-light1)',
    calendarDaysTextColor: 'var(--gds-color-text-neutral-light1)',
    panelHeaderDividerColor: 'var(--gds-color-border-neutral)',
    calendarDaysDividerColor: 'var(--gds-color-border-neutral)',
    calendarDividerColor: 'var(--gds-color-border-neutral)',
    panelActionDividerColor: 'var(--gds-color-border-neutral)',
    panelBoxShadow:
      '0px 0px 1px 0px rgba(222, 55, 26, 0.30), 0px 4px 8px -2px rgba(222, 55, 26, 0.25)',
    panelBorderRadius: 'var(--gds-border-radius-xs)',
    calendarTitleFontWeight: 500,
    scrollItemBorderRadius: 'var(--gds-border-radius-xs)',
    shortcutItemColor: 'var(--gds-color-text-neutral-light)',
    shortcutItemHoverColor: 'var(--gds-color-text-neutral)',
    iconColor: 'var(--gds-color-icon-neutral)',
    iconColorDisabled: 'var(--gds-color-icon-neutral-light)'
  },
  TimePicker: {
    itemColorHover: 'var(--gds-color-bg-primary-light1)'
  },
  Input: {
    heightXSmall: '22px',
    heightSmall: 'var(--gds-line-height-28)',
    heightMedium: 'var(--gds-line-height-36)',
    heightLarge: 'var(--gds-line-height-40)',
    fontSizeXSmall: 'var(--gds-font-size-12)',
    fontSizeSmall: 'var(--gds-font-size-14)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-16)',
    lineHeight: '1.6',
    borderRadius: 'var(--gds-border-radius-m)',
    iconSize: '16px',
    lineHeightTextarea: '1rem',
    countTextColorDisabled: 'var(--gds-color-text-neutral-light3)',
    countTextColor: 'var(--gds-color-text-neutral-light3)',
    textColorDisabled: 'var(--gds-color-text-neutral-light2)',
    textDecorationColor: 'var(--gds-color-text-neutral-light2)',
    caretColor: 'var(--gds-color-text-primary)',
    placeholderColor: 'var(--gds-color-text-neutral-light3)',
    border: '1px solid var(--gds-color-border-neutral-dark1)',
    borderDisabled: 'var(--gds-color-border-neutral-dark1)',
    borderHover: '1px solid var(--gds-color-border-neutral-dark3)',
    groupLabelBorder: '1px solid var(--gds-color-bg-neutral-dark1)',
    groupLabelColor: 'var(--gds-color-bg-light)',
    groupLabelTextColor: 'var(--gds-color-text-neutral)',
    inputBackgroundColor: 'var(--gds-color-bg-light)',
    backgroundColor: 'var(--gds-color-bg-light)',
    inputBorderColor: 'var(--gds-color-border-neutral-dark1)',
    textColor: 'var(--gds-color-text-neutral)',
    borderFocus: '1px solid var(--gds-color-border-primary)',
    // warning
    loadingColorWarning: 'var(--gds-color-border-warning-dark)',
    colorFocusWarning: 'var(--gds-color-bg-light)',
    caretColorWarning: 'var(--gds-color-icon-warning)',
    borderWarning: '1px solid var(--gds-color-border-warning)',
    borderHoverWarning: '1px solid var(--gds-color-border-warning-dark)',
    borderFocusWarning: '1px solid var(--gds-color-border-warning-dark)',
    boxShadowFocusWarning: '0 var(--gds-color-border-warning)',
    // error
    loadingColorError: 'var(--gds-color-border-danger-dark)',
    colorFocusError: 'var(--gds-color-bg-light)',
    caretColorError: 'var(--gds-color-icon-danger)',
    clearColor: 'var(--gds-color-icon-neutral)',
    clearColorHover: 'var(--gds-color-icon-neutral-dark1)',
    clearColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    iconColor: 'var(--gds-color-bg-dark)',
    iconColorDisabled: 'var(--gds-color-icon-neutral)',
    iconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    iconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    suffixTextColor: 'var(--gds-color-text-neutral-light2)',
    borderHoverError: '1px solid var(--gds-color-border-danger-dark)',
    borderFocusError: '1px solid var(--gds-color-border-danger-dark)',
    boxShadowFocusError: '0 var(--gds-color-border-danger)',
    borderError: '1px solid var(--gds-color-border-danger-dark)'
  },
  Alert: {
    borderInfo: '1px solid var(--gds-color-border-info)',
    borderNeutral: '1px solid var(--gds-color-border-neutral)',
    colorInfo: 'var(--gds-color-bg-info-light2)',
    titleTextColorInfo: 'var(--gds-color-text-neutral)',
    titleTextColorSuccess: 'var(--gds-color-text-neutral)',
    titleTextColorWarning: 'var(--gds-color-text-neutral)',
    titleTextColorError: 'var(--gds-color-text-neutral)',
    titleTextColorNeutral: 'var(--gds-color-text-neutral)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    contentTextColorInfo: 'var(--gds-color-text-neutral-light2)',
    contentTextColorSuccess: 'var(--gds-color-text-neutral-light2)',
    contentTextColorWarning: 'var(--gds-color-text-neutral-light2)',
    contentTextColorError: 'var(--gds-color-text-neutral-light2)',
    contentTextColorNeutral: 'var(--gds-color-text-neutral-light2)',
    closeIconColorInfo: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHoverInfo: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressedInfo: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorSuccess: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHoverSuccess: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressedSuccess: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorWarning: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHoverWarning: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressedWarning: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorError: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHoverError: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressedError: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorNeutral: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHoverNeutral: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressedNeutral: 'var(--gds-color-icon-neutral-dark1)',
    borderSuccess: '1px solid var(--gds-color-border-success)',
    colorSuccess: 'var(--gds-color-bg-success-light2)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    borderWarning: '1px solid var(--gds-color-border-warning)',
    colorWarning: 'var(--gds-color-bg-warning-light2)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    borderError: '1px solid var(--gds-color-border-danger)',
    colorError: 'var(--gds-color-bg-danger-light2)',
    iconColorError: 'var(--gds-color-icon-danger)',
    colorNeutral: 'var(--gds-color-bg-neutral-light)',
    iconColorNeutral: 'var(--gds-color-icon-neutral)'
  },
  Badge: {
    colorPrimary: 'var(--gds-color-icon-neutral)',
    colorInfo: 'var(--gds-color-icon-info)',
    colorSuccess: 'var(--gds-color-icon-success)',
    colorError: 'var(--gds-color-icon-danger)',
    colorWarning: 'var(--gds-color-icon-warning)'
  },
  Tag: {
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    heightXSmall: '16px',
    heightSmall: 'var(--gds-line-height-20)',
    heightMedium: 'var(--gds-line-height-24)',
    heightLarge: 'var(--gds-line-height-28)',
    borderRadius: 'var(--gds-border-radius-xs)',
    opacityDisabled: '0.4',
    fontSizeXSmall: 'var(--gds-font-size-12)',
    fontSizeSmall: 'var(--gds-font-size-12)',
    fontSizeMedium: 'var(--gds-font-size-14)',
    fontSizeLarge: 'var(--gds-font-size-14)',
    fontWeightStrong: 500,
    // checked
    borderChecked: '1px solid var(--gds-color-border-primary)',
    // focus
    borderFocused: 'var(--gds-color-border-primary)',
    // default
    iconColorNeutral: 'var(--gds-color-icon-neutral)',
    iconColorNeutralChecked: 'var(--gds-color-icon-neutral)',
    colorBorderedNeutral: 'var(--gds-color-border-neutral-light2)',
    colorPressedNeutral: 'var(--gds-color-bg-neutral-dark3)',
    closeColorHoverNeutral: 'var(--gds-color-bg-neutral)',
    closeColorPressedNeutral: 'var(--gds-color-bg-neutral-dark2)',
    borderNeutral: '1px solid var(--gds-color-border-neutral)',

    borderPrimary: '1px solid var(--gds-color-border-primary)',
    colorPressedPrimary: 'var(--gds-color-bg-primary-dark2)',
    closeColorHoverPrimary: 'var(--gds-color-bg-primary-light2)',
    closeColorPressedPrimary: 'var(--gds-color-bg-primary-light2)',

    colorPressedInfo: 'var(--gds-color-bg-info-light2)',
    closeColorHoverInfo: 'var(--gds-color-bg-info)',
    closeColorPressedInfo: 'var(--gds-color-bg-info)',
    colorPressedSuccess: 'var(--gds-color-bg-success-light2)',
    closeColorPressedSuccess: 'var(--gds-color-bg-success-light1)',
    colorPressedWarning: 'var(--gds-color-bg-warning-light2)',
    closeColorHoverWarning: 'var(--gds-color-bg-warning-light1)',
    closeColorPressedWarning: 'var(--gds-color-bg-warning-light1)',

    colorPressedError: 'var(--gds-color-bg-danger-light3)',
    closeColorHoverError: 'var(--gds-color-bg-danger-light2)',
    closeColorPressedError: 'var(--gds-color-bg-danger-light2)',

    colorSuccess: 'var(--gds-color-bg-light)',
    colorBorderedSuccess: 'var(--gds-color-bg-success-light2)',
    textColorPrimary: 'var(--gds-color-text-primary)',
    textColorPrimaryChecked: 'var(--gds-color-text-primary)',
    textColorPrimaryUnchecked: 'var(--gds-color-text-primary)',
    iconColorPrimary: 'var(--gds-color-icon-primary)',
    iconColorPrimaryChecked: 'var(--gds-color-icon-primary)',
    textColorSuccess: 'var(--gds-color-text-success)',
    textColorSuccessChecked: 'var(--gds-color-text-success)',
    textColorSuccessUnchecked: 'var(--gds-color-text-neutral)',
    iconColorSuccess: 'var(--gds-color-icon-success)',
    iconColorSuccessChecked: 'var(--gds-color-icon-success)',
    borderSuccess: '1px solid var(--gds-color-border-success)',
    colorWarning: 'var(--gds-color-bg-light)',
    colorBorderedWarning: 'var(--gds-color-bg-warning-light2)',
    textColorWarning: 'var(--gds-color-text-warning)',
    textColorWarningChecked: 'var(--gds-color-text-warning)',
    textColorWarningUnchecked: 'var(--gds-color-text-neutral)',
    iconColorWarning: 'var(--gds-color-icon-warning)',
    iconColorWarningChecked: 'var(--gds-color-icon-warning)',
    borderWarning: '1px solid var(--gds-color-border-warning)',
    colorError: 'var(--gds-color-bg-light)',
    colorBorderedError: 'var(--gds-color-bg-danger-light2)',
    textColorError: 'var(--gds-color-text-danger)',
    textColorErrorChecked: 'var(--gds-color-text-danger)',
    textColorErrorUnchecked: 'var(--gds-color-text-neutral)',
    iconColorError: 'var(--gds-color-icon-danger)',
    iconColorErrorChecked: 'var(--gds-color-icon-danger)',
    borderError: '1px solid var(--gds-color-bg-neutral-dark1)',
    colorPrimary: 'var(--gds-color-bg-light)',
    colorInfo: 'var(--gds-color-bg-light)',
    colorNeutral: 'var(--gds-color-bg-light)',
    colorBorderedInfo: 'var(--gds-color-bg-info-light2)',
    colorBorderedPrimary: 'var(--gds-color-bg-info-light2))',
    textColorNeutral: 'var(--gds-color-text-neutral)',
    textColorNeutralChecked: 'var(--gds-color-text-info)',
    textColorNeutralUnchecked: 'var(--gds-color-text-neutral)',
    textColorInfo: 'var(--gds-color-text-info)',
    textColorInfoChecked: 'var(--gds-color-text-info)',
    textColorInfoUnchecked: 'var(--gds-color-text-info-neutral)',
    iconColorInfo: 'var(--gds-color-icon-info)',
    iconColorInfoChecked: 'var(--gds-color-icon-info)',
    colorCheckedPrimary: 'var(--gds-color-bg-info-light2)',
    colorCheckedError: 'var(--gds-color-bg-danger-light2)',
    colorCheckedWarning: 'var(--gds-color-bg-warning-light2)',
    colorCheckedInfo: 'var(--gds-color-bg-info-light2)',
    colorCheckedSuccess: 'var(--gds-color-bg-success-light2)',
    colorCheckedNeutral: 'var(--gds-color-bg-info-light2)',
    colorHoverPrimary: 'var(--gds-color-bg-neutral-dark1)',
    colorHoverError: 'var(--gds-color-bg-neutral-dark1)',
    colorHoverWarning: 'var(--gds-color-bg-neutral-dark1)',
    colorHoverInfo: 'var(--gds-color-bg-neutral-dark1)',
    colorHoverSuccess: 'var(--gds-color-bg-neutral-dark1)',
    colorHoverNeutral: 'var(--gds-color-bg-neutral-dark1)',
    borderInfo: '1px solid var(--gds-color-border-info)',
    checkedBorderedInfo: '1px solid var(--gds-color-bg-primary)',
    checkedBorderedError: '1px solid var(--gds-color-bg-danger)',
    checkedBorderedSuccess: '1px solid var(--gds-color-bg-success)',
    checkedBorderedNeutral: '1px solid var(--gds-color-bg-primary)',
    checkedBorderedPrimary: '1px solid var(--gds-color-bg-primary)',
    checkedBorderedWarning: '1px solid var(--gds-color-border-warning)',
    badgeBorderColorPrimary: 'var(--gds-color-bg-primary)',
    badgeBorderColorPrimaryChecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorPrimaryUnchecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorInfo: 'var(--gds-color-border-primary)',
    badgeBorderColorInfoChecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorInfoUnchecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorNeutral: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorNeutralChecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorNeutralUnchecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorSuccess: 'var(--gds-color-border-success)',
    badgeBorderColorSuccessChecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorSuccessUnchecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorWarning: 'var(--gds-color-border-warning)',
    badgeBorderColorWarningChecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorWarningUnchecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorError: 'var(--gds-color-icon-danger)',
    badgeBorderColorErrorChecked: 'var(--gds-color-border-neutral-dark1)',
    badgeBorderColorErrorUnchecked: 'var(--gds-color-border-neutral-dark1)',
    closeIconColorNeutral: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverNeutral: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedNeutral: 'var(--gds-color-icon-neutral)',
    closeIconColorPrimary: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverPrimary: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedPrimary: 'var(--gds-color-icon-neutral)',
    closeIconColorInfo: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverInfo: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedInfo: 'var(--gds-color-icon-neutral)',
    closeIconColorSuccess: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverSuccess: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedSuccess: 'var(--gds-color-icon-neutral)',
    closeIconColorWarning: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverWarning: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedWarning: 'var(--gds-color-icon-neutral)',
    closeIconColorError: 'var(--gds-color-icon-neutral)',
    closeIconColorHoverError: 'var(--gds-color-icon-neutral)',
    closeIconColorPressedError: 'var(--gds-color-icon-neutral)'
  },
  Stepper: {
    descriptionTextColorError: 'var(--gds-color-text-neutral-light1)',
    descriptionTextColorFinish: 'var(--gds-color-text-neutral-light1)',
    descriptionTextColorProcess: 'var(--gds-color-text-neutral-light1)',
    hoverDescriptionColorError: 'var(--gds-color-text-neutral-light1)',
    hoverDescriptionColorProcess: 'var(--gds-color-text-neutral-light1)',
    hoverDescriptionColorFinish: 'var(--gds-color-text-neutral-light1)',
    indicatorColorError: 'var(--gds-color-icon-danger)',
    indicatorIconColorProcess: 'var(--gds-color-bg-dark)',
    indicatorIconColorWait: 'var(--gds-color-icon-neutral-light)',
    indicatorIconColorFinish: 'var(--gds-color-icon-success)',
    indicatorIconColorError: 'var(--gds-color-icon-danger)',
    indicatorColorWait: 'var(--gds-color-bg-light)',
    indicatorBorderColorWait: 'var(--gds-color-border-neutral-dark1)',
    hoverIndicatorColorError: 'var(--gds-color-icon-danger)',
    splitorColorError: 'var(--gds-color-border-neutral-dark1)',
    splitorColorProcess: 'var(--gds-color-border-neutral-dark1)',
    splitorColorWait: 'var(--gds-color-border-neutral-dark1)',
    hoverDesciptionColorWait: 'unset',
    hoverIndicatorColorWait: 'var(--gds-color-bg-neutral)',
    hoverTextColorWait: 'var(--gds-color-text-neutral-light1)',
    splitorColorFinish: 'var(--gds-color-icon-success)',
    indicatorColorProcess: 'var(--gds-color-bg-dark)',
    hoverIndicatorColorProcess: 'var(--gds-color-bg-neutral-dark4)',
    indicatorColorFinish: 'var(--gds-color-icon-success)',
    indicatorTextColorProcess: 'var(--gds-color-text-button-primary)',
    indicatorTextColorWait: 'var(--gds-color-text-neutral-light2)',
    indicatorTextColorFinish: 'var(--gds-color-icon-success)',
    indicatorTextColorError: 'var(--gds-color-icon-danger)',
    headerTextColorProcess: 'var(--gds-color-text-neutral-light1)',
    headerTextColorWait: 'var(--gds-color-text-neutral-light2)',
    headerTextColorFinish: 'var(--gds-color-text-neutral-light1)',
    headerTextColorError: 'var(--gds-color-text-danger-light1)',
    hoverTextColorProcess: 'var(--gds-color-text-neutral-light1)',
    hoverTextColorFinish: 'var(--gds-color-text-neutral-light1)',
    hoverTextColorError: 'var(--gds-color-text-neutral-light1)',
    descriptionTextColorWait: 'var(--gds-color-text-neutral-light2)',
    hoverIndicatorColorFinish: 'var(--gds-color-bg-success)',
    hoverDescriptionColorWait: 'var(--gds-color-text-neutral-light1)'
  },
  Panel: {
    iconColor: 'var(--gds-color-icon-neutral-dark1)',
    textColor: 'var(--gds-color-text-neutral-light2)',
    dividerColor: 'var(--gds-color-border-neutral)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    baseColor: 'var(--gds-color-bg-light)',
    paginationTextColor: 'var(--gds-color-text-neutral-light2)'
  },
  Link: {
    color: 'var(--gds-color-text-info)',
    colorDefault: 'var(--gds-color-text-info)',
    colorActive: 'var(--gds-color-text-info-dark2)',
    colorVisited: 'var(--gds-color-text-support-violet-light)',
    colorHover: 'var(--gds-color-text-info-dark1)',
    colorFocus: 'var(--gds-color-border-primary-light)',
    fontSize: 'var(--gds-font-size-14)',
    lineHeight: 'var(--gds-line-height-16)',
    fontWeight: 500
  },
  Filter: {
    fontSize: 'var(--gds-font-size-14)',
    textColor: 'var(--gds-color-text-neutral)',
    valueTextColor: 'var(--gds-color-text-primary)',
    tagBackgroundColor: 'var(--gds-color-bg-light)',
    labelTextColor: 'var(--gds-color-text-neutral)',
    actionBorderColor: 'var(--gds-color-border-neutral-dark2)',
    resetTextColor: 'var(--gds-color-text-neutral-light2)',
    resetColorHover: 'var(--gds-color-text-neutral-light1)',
    tagHoverColor: 'var(--gds-color-bg-neutral-dark1)',
    tagActiveColor: 'var(--gds-color-bg-neutral)',
    resetColor: 'var(--gds-color-icon-neutral)'
  },
  Form: {
    blankHeightSmall: '28px',
    blankHeightMedium: '34px',
    blankHeightLarge: '40px',
    lineHeight: '1.6',
    inputBackgroundColor: 'var(--gds-color-bg-neutral)',
    labelTextColor: 'var(--gds-color-text-neutral-light1)',
    labelDescriptionTextColor: 'var(--gds-color-text-neutral-light2)',
    helpIconColor: 'var(--gds-color-icon-neutral)',
    asteriskColor: 'var(--gds-color-icon-danger)',
    feedbackTextColorSuccess: 'var(--gds-color-text-success)',
    feedbackTextColorNeutral: 'var(--gds-color-text-neutral)',
    feedbackTextColorError: 'var(--gds-color-text-danger)',
    feedbackTextColorWarning: 'var(--gds-color-text-warning)',
    feedbackIconColorNeutral: 'var(--gds-color-icon-neutral)',
    feedbackIconColorWarning: 'var(--gds-color-icon-warning)',
    feedbackIconColorError: 'var(--gds-color-icon-danger)',
    feedbackIconColorSuccess: 'var(--gds-color-icon-success)',
    feedbackTextColor: 'var(--gds-color-text-neutral)'
  },
  DetailsView: {
    detailsViewLabelColor: 'var(--gds-color-text-neutral-light2)',
    detailsViewValueColor: 'var(--gds-color-text-neutral-light1)',
    color: 'var(--gds-color-bg-light)',
    dividerColor: 'var(--gds-color-border-neutral)',
    expandedBackgroundColor: 'var(--gds-color-bg-light)',
    textColor: 'var(--gds-color-text-primary)',
    titleTextColor: 'var(--gds-color-text-neutral)'
  },
  Scrollbar: {
    color: 'var(--gds-color-bg-neutral-dark2)',
    colorHover: 'var(--gds-color-bg-neutral-dark3)',
    scrollBoxShadowColor: 'rgba(2, 13, 75, 0.1)'
  },
  List: {
    textColor: 'var(--gds-color-text-neutral)',
    colorHover: 'var(--gds-color-bg-neutral)',
    selectedColor: 'var(--gds-color-bg-primary-light2)',
    borderColor: 'var(--gds-color-border-neutral)',
    color: 'var(--gds-color-bg-light)',
    colorModal: 'var(--gds-color-bg-light)',
    colorPopover: 'var(--gds-color-bg-light)',
    borderRadius: 'var(--gds-border-radius-xs)',
    fontSize: 'var(--gds-font-size-14)',
    colorHoverPopover: 'var(--gds-color-bg-light)',
    colorHoverModal: 'var(--gds-color-bg-light)',
    borderColorModal: 'var(--gds-color-border-neutral)',
    borderColorPopover: 'var(--gds-color-border-neutral)'
  },
  Divider: {
    textColor: 'var(--gds-color-text-neutral)',
    color: 'var(--gds-color-border-neutral)'
  },
  Facade: {
    titleTextColor: 'var(--gds-color-text-neutral)',
    textColor: 'var(--gds-color-text-neutral-light2)',
    fontSize: 'var(--gds-font-size-14)'
  },
  Upload: {
    fontSize: 'var(--gds-font-size-14)',
    lineHeight: '1.6',
    borderRadius: 'var(--gds-border-radius-xxl)',
    draggerBorder: '1px dashed var(--gds-color-border-neutral-dark2)',
    itemBorderImageCardError: '1px solid var(--gds-color-border-danger-dark)',
    itemBorderImageCard: '1px solid var(--gds-color-border-neutral)',
    draggerBorderHover: '1px solid var(--gds-color-border-primary-light)',
    draggerBorderPressed: '2px solid var(--gds-color-border-primary)',
    draggerColor: 'var(--gds-color-bg-neutral-light)',
    itemColorHover: 'var(--gds-color-bg-neutral-dark1)',
    itemColorHoverError: 'var(--gds-color-bg-danger-light3)',
    itemTextColor: 'var(--gds-color-text-neutral)',
    itemTextColorError: 'var(--gds-color-text-danger)',
    itemTextColorSuccess: 'var(--gds-color-text-success)',
    itemIconColor: 'var(--gds-color-icon-neutral)',
    trashIconColor: 'var(--gds-color-icon-danger)',
    downloadTextColor: 'var(--gds-color-text-primary)',
    uploaderBorderColor: 'var(--gds-color-border-neutral-dark2)',
    itemDisabledOpacity: '40%',
    uploaderListBorderRadius: 'var(--gds-border-radius-xxl)'
  },
  Image: {
    toolbarIconColor: 'var(--gds-color-icon-inverse)',
    toolbarColor: 'var(--gds-color-bg-primary-dark2)',
    opacity: 0.4
  },
  FloatingPanel: {
    borderRadius: 'var(--gds-border-radius-m)',
    lineHeight: '1.6',
    fontSize: 'var(--gds-font-size-14)',
    headerFontWeight: 500,
    descriptionFontSize: ' var(--gds-font-size-14)',
    closeBorderRadius: 'var(--gds-border-radius-xs)',
    toggleBorderRadius: 'var(--gds-border-radius-xs)',
    newTabBorderRadius: 'var(--gds-border-radius-xs)',
    iconColor: 'var(--gds-color-icon-neutral)',
    color: 'var(--gds-color-bg-light)',
    panelDividerColor: 'var(--gds-color-border-neutral)',
    textColor: 'var(--gds-color-text-neutral)',
    closeIconColor: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    closeIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    closeColorHover: 'var(--gds-color-bg-button-static-tertiary-dark1)',
    closeColorPressed: 'var(--gds-color-bg-button-static-tertiary-dark2)',
    toggleColorHover: 'var(--gds-color-bg-button-static-tertiary-dark1)',
    toggleColorPressed: 'var(--gds-color-bg-button-static-tertiary-dark2)',
    toggleIconColor: 'var(--gds-color-icon-neutral-dark1)',
    toggleIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    toggleIconColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    newTabColorHover: 'var(--gds-color-bg-button-static-tertiary-dark1)',
    newTabColorPressed: 'var(--gds-color-bg-button-static-tertiary-dark2)',
    newTabIconColor: 'var(--gds-color-icon-neutral-dark1)',
    newTabIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    newTabIconColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    toolbarBackgroundColor: 'var(--gds-color-bg-primary)',
    toolbarBackgroundColorHover: 'var(--gds-color-bg-primary-dark1)',
    headerTextColor: 'var(--gds-color-text-neutral)',
    actionTextColor: 'var(--gds-color-text-neutral)'
  },
  Pagination: {
    itemSizeSmall: '22px',
    itemSizeMedium: '36px',
    itemSizeLarge: '34px',
    buttonColor: 'var(--gds-color-bg-button-secondary)',
    buttonColorHover: 'var(--gds-color-bg-button-secondary-dark1)',
    buttonColorPressed: 'var(--gds-color-bg-button-secondary-dark2)',
    buttonIconColor: 'var(--gds-color-icon-neutral-dark1)',
    buttonIconColorHover: 'var(--gds-color-icon-neutral-dark1)',
    buttonIconColorPressed: 'var(--gds-color-icon-neutral-dark1)',
    itemTextColor: 'var(--gds-color-text-neutral)',
    itemTextColorHover: 'var(--gds-color-text-neutral)',
    itemTextColorPressed: 'var(--gds-color-text-neutral)',
    itemTextColorActive: 'var(--gds-color-text-neutral)',
    itemTextColorDisabled: 'var(--gds-color-text-neutral-light3)',
    itemColor: 'var(--gds-color-bg-light)',
    itemColorHover: 'var(--gds-color-border-neutral)',
    itemColorPressed: 'var(--gds-color-border-neutral)',
    itemColorActive: 'var(--gds-color-border-neutral)',
    itemColorActiveHover: 'var(--gds-color-border-neutral)',
    itemColorDisabled: 'var(--gds-color-bg-light)',
    itemBorderRadius: 'var(--gds-border-radius-xs)',
    itemFontSizeSmall: 'var(--gds-font-size-12)',
    itemFontSizeMedium: 'var(--gds-font-size-14)',
    itemFontSizeLarge: 'var(--gds-font-size-14)',
    jumperFontSizeSmall: 'var(--gds-font-size-12)',
    jumperFontSizeMedium: 'var(--gds-font-size-14)',
    jumperFontSizeLarge: 'var(--gds-font-size-14)',
    jumperTextColor: 'var(--gds-color-text-neutral)',
    jumperTextColorDisabled: 'var(--gds-color-text-neutral-light1)',
    clearColor: 'var(--gds-color-icon-neutral)',
    clearColorHover: 'var(--gds-color-icon-neutral-dark1)',
    clearColorPressed: 'var(--gds-color-icon-neutral-dark2)',
    arrowColor: 'var(--gds-color-icon-neutral)',
    buttonBorder: '1px solid var(--gds-color-border-button-secondary)',
    buttonBorderHover:
      '1px solid var(--gds-color-border-button-secondary-dark1)',
    buttonBorderPressed:
      '1px solid var(--gds-color-border-button-secondary-dark2)',
    itemBorderActive: '1px solid var(--gds-color-border-primary)',
    itemBorderDisabled: '1px solid var(--gds-color-border-primary)',
    itemBorder: '1px solid var(--gds-color-border-neutral)',
    itemBorderHover: '1px solid var(--gds-color-border-neutral)',
    itemBorderPressed: '1px solid var(--gds-color-border-neutral)'
  },
  Modal: {
    color: 'var(--gds-color-bg-light)',
    textColor: 'var(--gds-color-text-neutral)'
  },
  Popover: {
    fontSize: 'var(--gds-font-size-14)',
    borderRadius: 'var(--gds-border-radius-xs)',
    dividerColor: 'var(--gds-color-border-neutral)',
    bgColor: 'var(--gds-color-bg-light)',
    textColor: 'var(--gds-color-text-neutral)'
  }
}
