export default {
  feedbackPadding: '4px 0 0 0',
  feedbackHeightSmall: '24px',
  feedbackHeightMedium: '24px',
  feedbackHeightLarge: '26px',
  feedbackFontSizeSmall: '12px',
  feedbackFontSizeMedium: '12px',
  feedbackFontSizeLarge: '14px',
  feedbackIconSizeSmall: '14px',
  feedbackIconSizeMedium: '16px',
  feedbackIconSizeLarge: '18px',
  labelFontSizeLeftSmall: '12px',
  labelFontSizeLeftMedium: '14px',
  labelFontSizeLeftLarge: '16px',
  labelFontSizeTopSmall: '12px',
  labelFontSizeTopMedium: '14px',
  labelFontSizeTopLarge: '16px',
  labelDescriptionFontSizeSmall: '12px',
  labelDescriptionFontSizeMedium: '12px',
  labelDescriptionFontSizeLarge: '14px',
  labelHeightSmall: '24px',
  labelHeightMedium: '26px',
  labelHeightLarge: '28px',
  labelPaddingVertical: '0 0 4px 0',
  labelPaddingHorizontal: '0 12px 0 0',
  labelTextAlignVertical: 'left',
  labelTextAlignHorizontal: 'right',
  labelFontWeight: '400'
}
