export default {
  paddingXSmall: '4px 8px',
  paddingSmall: '8px 10px',
  paddingMedium: '8px 12px',
  paddingLarge: '8px 14px',
  paddingXLarge: '8px 16px',
  paddingRoundXSmall: '0 10px',
  paddingRoundSmall: '0 14px',
  paddingRoundMedium: '0 18px',
  paddingRoundLarge: '0 22px',
  paddingRoundXLarge: '0 22px',
  paddingIconOnly: '7px 8px',
  iconMarginXSmall: '6px 2px',
  iconMarginSmall: '6px 2px',
  iconMarginMedium: '6px 2px',
  iconMarginLarge: '6px 2px',
  iconMarginXLarge: '6px 2px',
  iconSizeXSmall: '16px',
  iconSizeSmall: '20px',
  iconSizeMedium: '20px',
  iconSizeLarge: '20px',
  iconSizeXLarge: '20px',
  rippleDuration: '.6s'
}
