import commonVariables from './_common'
import { commonLight } from '../../_styles/common'
import type { ThemeCommonVars } from '../../_styles/common'
import type { Theme } from '../../_mixins'

export const self = (vars: ThemeCommonVars) => {
  const {
    heightXSmall,
    heightSmall,
    heightMedium,
    heightLarge,
    heightXLarge,
    borderRadius,
    fontSizeXSmall,
    fontSizeSmall,
    fontSizeMedium,
    fontSizeLarge,
    fontSizeXLarge,
    opacityDisabled,
    textColor2,
    textColor3,
    primaryColorHover,
    primaryColorPressed,
    borderColor,
    primaryColor,
    baseColor,
    infoColor,
    infoColorHover,
    infoColorPressed,
    successColor,
    successColorHover,
    successColorPressed,
    warningColor,
    warningColorHover,
    warningColorPressed,
    errorColor,
    errorColorHover,
    errorColorPressed,
    fontWeight,
    buttonColor2,
    buttonColor2Hover,
    buttonColor2Pressed,
    fontWeightStrong
  } = vars
  return {
    ...commonVariables,
    heightXSmall,
    heightSmall,
    heightMedium,
    heightLarge,
    heightXLarge,
    elevationLevel4:
      '0px 0px 1px 0px hsla(231, 95%, 15%, 0.30) , 0px 8px 16px -4px hsla(231, 95%, 15%, 0.25)',
    elevationLevel3:
      '0px 4px 8px -2px hsla(231, 95%, 15%, 0.25) , 0px 0px 1px 0px hsla(231, 95%, 15%, 0.30)',
    elevationLevel2:
      '0px 2px 5px 0px hsla(231, 95%, 15%, 0.10) , 0px -2px 5px 0px hsla(231, 95%, 15%, 0.10)',
    elevationLevel1:
      '0px 0px 1px 0px hsla(231, 95%, 15%, 0.30) , 0px 1px 1px 0px hsla(231, 95%, 15%, 0.25)',
    elevationLevel0: '0px',
    borderRadiusXSmall: borderRadius,
    borderRadiusSmall: borderRadius,
    borderRadiusMedium: borderRadius,
    borderRadiusLarge: borderRadius,
    borderRadiusXLarge: borderRadius,
    fontSizeXSmall,
    fontSizeSmall,
    fontSizeMedium,
    fontSizeLarge,
    fontSizeXLarge,
    opacityDisabled,

    // secondary
    colorOpacitySecondary: '0.16',
    colorOpacitySecondaryHover: '0.1',
    colorOpacitySecondaryPressed: '0.3',
    colorSecondary: buttonColor2,
    colorSecondaryHover: buttonColor2Hover,
    colorSecondaryPressed: buttonColor2Pressed,
    // tertiary
    colorTertiary: buttonColor2,
    colorTertiaryHover: buttonColor2Hover,
    colorTertiaryPressed: buttonColor2Pressed,
    // quaternary
    colorQuaternary: '#0000',
    colorQuaternaryHover: buttonColor2Hover,
    colorQuaternaryPressed: buttonColor2Pressed,
    // default type
    colorDefault: '#FFF',

    color: '#868e96',
    colorHover: '#495057',
    colorPressed: '#495057',
    colorFocus: '#495057',
    colorDisabled: '#0000',
    // filled
    textColorFilled: baseColor,
    iconColorFilled: baseColor,
    textColorHoverFilled: baseColor,
    textColorPressedFilled: baseColor,
    textColorFocusFilled: baseColor,
    textColorDisabledFilled: baseColor,
    textColorFilledNeutral: baseColor,
    iconColorFilledNeutral: baseColor,
    textColorHoverFilledNeutral: baseColor,
    textColorPressedFilledNeutral: baseColor,
    textColorFocusFilledNeutral: baseColor,
    textColorDisabledFilledNeutral: baseColor,
    textColorFilledPrimary: baseColor,
    iconColorFilledPrimary: baseColor,
    textColorHoverFilledPrimary: baseColor,
    textColorPressedFilledPrimary: baseColor,
    textColorFocusFilledPrimary: baseColor,
    textColorDisabledFilledPrimary: baseColor,
    textColorFilledInfo: baseColor,
    iconColorFilledInfo: baseColor,
    textColorHoverFilledInfo: baseColor,
    textColorPressedFilledInfo: baseColor,
    textColorFocusFilledInfo: baseColor,
    textColorDisabledFilledInfo: baseColor,
    textColorFilledSuccess: baseColor,
    iconColorFilledSuccess: baseColor,
    textColorHoverFilledSuccess: baseColor,
    textColorPressedFilledSuccess: baseColor,
    textColorFocusFilledSuccess: baseColor,
    textColorDisabledFilledSuccess: baseColor,
    textColorFilledWarning: baseColor,
    iconColorFilledWarning: baseColor,
    textColorHoverFilledWarning: baseColor,
    textColorPressedFilledWarning: baseColor,
    textColorFocusFilledWarning: baseColor,
    textColorDisabledFilledWarning: baseColor,
    textColorFilledError: baseColor,
    iconColorFilledError: baseColor,
    textColorHoverFilledError: baseColor,
    textColorPressedFilledError: baseColor,
    textColorFocusFilledError: baseColor,
    textColorDisabledFilledError: baseColor,
    colorOutlinedHover: undefined,
    colorOutlinedHoverPrimary: undefined,
    colorOutlinedHoverInfo: undefined,
    colorOutlinedHoverSuccess: undefined,
    colorOutlinedHoverWarning: undefined,
    colorOutlinedHoverError: undefined,
    colorOutlinedHoverNeutral: undefined,

    colorOutlinedPressed: undefined,
    colorOutlinedPressedPrimary: undefined,
    colorOutlinedPressedInfo: undefined,
    colorOutlinedPressedSuccess: undefined,
    colorOutlinedPressedWarning: undefined,
    colorOutlinedPressedError: undefined,
    colorOutlinedPressedNeutral: undefined,

    colorOutlinedFocus: undefined,
    colorOutlinedFocusPrimary: undefined,
    colorOutlinedFocusInfo: undefined,
    colorOutlinedFocusSuccess: undefined,
    colorOutlinedFocusWarning: undefined,
    colorOutlinedFocusError: undefined,
    colorOutlinedFocusNeutral: undefined,

    colorSubtleHover: undefined,
    colorSubtleHoverPrimary: undefined,
    colorSubtleHoverInfo: undefined,
    colorSubtleHoverSuccess: undefined,
    colorSubtleHoverWarning: undefined,
    colorSubtleHoverError: undefined,
    colorSubtleHoverNeutral: undefined,

    colorSubtlePressed: undefined,
    colorSubtlePressedPrimary: undefined,
    colorSubtlePressedInfo: undefined,
    colorSubtlePressedSuccess: undefined,
    colorSubtlePressedWarning: undefined,
    colorSubtlePressedError: undefined,
    colorSubtlePressedNeutral: undefined,

    colorSubtleFocus: undefined,
    colorSubtleFocusPrimary: undefined,
    colorSubtleFocusInfo: undefined,
    colorSubtleFocusSuccess: undefined,
    colorSubtleFocusWarning: undefined,
    colorSubtleFocusNeutral: undefined,
    colorSubtleFocusError: undefined,

    // outlined text color
    textColorOutlinedPrimary: primaryColor,
    textColorOutlinedNeutral: primaryColor,
    textColorOutlinedInfo: infoColor,
    textColorOutlinedSuccess: primaryColor,
    textColorOutlinedError: infoColor,
    textColorOutlinedWarning: primaryColor,
    iconColorOutlinedPrimary: primaryColor,
    iconColorOutlinedNeutral: primaryColor,
    iconColorOutlinedInfo: infoColor,
    iconColorOutlinedSuccess: primaryColor,
    iconColorOutlinedError: infoColor,
    iconColorOutlinedWarning: '#00FF00',
    // tertiary text color
    textColorTertiaryPrimary: primaryColor,
    textColorTertiaryNeutral: primaryColor,
    textColorTertiaryInfo: infoColor,
    textColorTertiarySuccess: primaryColor,
    textColorTertiaryError: infoColor,
    textColorTertiaryWarning: primaryColor,
    iconColorTertiaryPrimary: primaryColor,
    iconColorTertiaryNeutral: primaryColor,
    iconColorTertiaryInfo: infoColor,
    iconColorTertiarySuccess: primaryColor,
    iconColorTertiaryError: infoColor,
    iconColorTertiaryWarning: primaryColor,

    // primary
    colorPrimary: primaryColor,
    colorHoverPrimary: primaryColorHover,
    colorPressedPrimary: primaryColorPressed,
    colorFocusPrimary: primaryColorHover,
    colorDisabledPrimary: primaryColor,
    // info
    colorInfo: infoColor,
    colorHoverInfo: infoColorHover,
    colorPressedInfo: infoColorPressed,
    colorFocusInfo: infoColorHover,
    colorDisabledInfo: infoColor,
    // error
    colorError: errorColor,
    colorHoverError: errorColorHover,
    colorPressedError: errorColorPressed,
    colorFocusError: errorColorHover,
    colorDisabledError: errorColor,
    // success
    colorSuccess: successColor,
    colorHoverSuccess: successColorHover,
    colorPressedSuccess: successColorPressed,
    colorFocusSuccess: successColorHover,
    colorDisabledSuccess: successColor,
    // warning
    colorWarning: warningColor,
    colorHoverWarning: warningColorHover,
    colorPressedWarning: warningColorPressed,
    colorFocusWarning: warningColorHover,
    colorDisabledWarning: warningColor,

    textColor: textColor2,
    iconColor: textColor2,
    textColorTertiary: textColor3, // tertiary
    textColorHover: primaryColorHover,
    textColorPressed: primaryColorPressed,
    textColorFocus: primaryColorHover,
    textColorDisabled: textColor2,
    textColorText: textColor2,
    iconColorText: textColor2,
    textColorTextHover: primaryColorHover,
    textColorTextPressed: primaryColorPressed,
    textColorTextFocus: primaryColorHover,
    textColorTextDisabled: textColor2,
    rippleColor: primaryColor,
    // default type
    colorDefaultNeutral: '#FFF',
    colorNeutral: '#868e96',
    colorHoverNeutral: '#495057',
    colorPressedNeutral: '#495057',
    colorFocusNeutral: '#495057',
    colorDisabledNeutral: '#0000',

    textColorNeutral: textColor2,
    textColorHoverNeutral: primaryColorHover,
    textColorPressedNeutral: primaryColorPressed,
    textColorFocusNeutral: primaryColorHover,
    textColorDisabledNeutral: textColor2,
    iconColorTextNeutral: textColor2,
    textColorTextNeutral: textColor2,
    textColorTextHoverNeutral: primaryColorHover,
    textColorTextPressedNeutral: primaryColorPressed,
    textColorTextFocusNeutral: primaryColorHover,
    textColorTextDisabledNeutral: textColor2,

    rippleColorNeutral: primaryColor,
    // link
    linkColorHover: primaryColor,
    linkColorActive: primaryColor,

    iconColorTextPrimary: primaryColor,
    textColorTextPrimary: primaryColor,
    textColorTextHoverPrimary: primaryColorHover,
    textColorTextPressedPrimary: primaryColorPressed,
    textColorTextFocusPrimary: primaryColorHover,
    textColorTextDisabledPrimary: textColor2,

    rippleColorPrimary: primaryColor,

    iconColorTextInfo: infoColor,
    textColorTextInfo: infoColor,
    textColorTextHoverInfo: infoColorHover,
    textColorTextPressedInfo: infoColorPressed,
    textColorTextFocusInfo: infoColorHover,
    textColorTextDisabledInfo: textColor2,

    rippleColorInfo: infoColor,

    iconColorTextSuccess: successColor,
    textColorTextSuccess: successColor,
    textColorTextHoverSuccess: successColorHover,
    textColorTextPressedSuccess: successColorPressed,
    textColorTextFocusSuccess: successColorHover,
    textColorTextDisabledSuccess: textColor2,

    rippleColorSuccess: successColor,
    iconColorTextWarning: warningColor,
    textColorTextWarning: warningColor,
    textColorTextHoverWarning: warningColorHover,
    textColorTextPressedWarning: warningColorPressed,
    textColorTextFocusWarning: warningColorHover,
    textColorTextDisabledWarning: textColor2,

    rippleColorWarning: warningColor,

    iconColorTextError: errorColor,
    textColorTextError: errorColor,
    textColorTextHoverError: errorColorHover,
    textColorTextPressedError: errorColorPressed,
    textColorTextFocusError: errorColorHover,
    textColorTextDisabledError: textColor2,

    border: `1px solid ${borderColor}`,
    borderHover: `1px solid ${primaryColorHover}`,
    borderPressed: `1px solid ${primaryColorPressed}`,
    borderFocus: `1px solid ${primaryColorHover}`,
    borderDisabled: `1px solid ${borderColor}`,

    borderNeutral: `1px solid ${borderColor}`,
    borderHoverNeutral: `1px solid ${primaryColorHover}`,
    borderPressedNeutral: `1px solid ${primaryColorPressed}`,
    borderFocusNeutral: `1px solid ${primaryColorHover}`,
    borderDisabledNeutral: `1px solid ${borderColor}`,

    borderPrimary: `1px solid ${primaryColor}`,
    borderHoverPrimary: `1px solid ${primaryColorHover}`,
    borderPressedPrimary: `1px solid ${primaryColorPressed}`,
    borderFocusPrimary: `1px solid ${primaryColorHover}`,
    borderDisabledPrimary: `1px solid ${primaryColor}`,

    borderInfo: `1px solid ${infoColor}`,
    borderHoverInfo: `1px solid ${infoColorHover}`,
    borderPressedInfo: `1px solid ${infoColorPressed}`,
    borderFocusInfo: `1px solid ${infoColorHover}`,
    borderDisabledInfo: `1px solid ${infoColor}`,

    borderSuccess: `1px solid ${successColor}`,
    borderHoverSuccess: `1px solid ${successColorHover}`,
    borderPressedSuccess: `1px solid ${successColorPressed}`,
    borderFocusSuccess: `1px solid ${successColorHover}`,
    borderDisabledSuccess: `1px solid ${successColor}`,

    borderWarning: `1px solid ${warningColor}`,
    borderHoverWarning: `1px solid ${warningColorHover}`,
    borderPressedWarning: `1px solid ${warningColorPressed}`,
    borderFocusWarning: `1px solid ${warningColorHover}`,
    borderDisabledWarning: `1px solid ${warningColor}`,

    borderError: `1px solid ${errorColor}`,
    borderHoverError: `1px solid ${errorColorHover}`,
    borderPressedError: `1px solid ${errorColorPressed}`,
    borderFocusError: `1px solid ${errorColorHover}`,
    borderDisabledError: `1px solid ${errorColor}`,

    rippleColorError: errorColor,
    waveOpacity: '0.6',
    fontWeight,
    fontWeightStrong,
    // focus
    focusColor: primaryColor
  }
}

export type ButtonThemeVars = ReturnType<typeof self>

const buttonLight: Theme<'Button', ButtonThemeVars> = {
  name: 'Button',
  common: commonLight,
  self
}

export default buttonLight
export type ButtonTheme = typeof buttonLight
